<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{

    public function run()
    {
        //
 DB::table('cities')->delete();
$cities = array(
     array('id' => 1, 'isim' => 'Çukurova', 'state_id' => 6410),

            array('id' => 2, 'isim' => 'Girne', 'state_id' => 6410),
            array('id' => 3,'isim' => 'Karaisali', 'state_id' => 6410),
            array('id' => 4,'isim' => 'Karatas', 'state_id' => 6410),
            array('id' => 5,'isim' => 'Seyhan', 'state_id' => 6410),
            array('id' => 6,'isim' => 'Yumurtalik', 'state_id' => 6410),
            array('id' => 7,'isim' => 'Aladag(Karsanti)', 'state_id' => 6410),
            array('id' => 8,'isim' => 'Ceyhan', 'state_id' => 6410),
            array('id' => 9,'isim' => 'Feke', 'state_id' => 6410),
            array('id' => 10,'isim' => 'Imamoglu', 'state_id' => 6410),
            array('id' => 11,'isim' => 'Kozan', 'state_id' => 6410),
            array('id' => 12,'isim' => 'Tufanbeyli', 'state_id' => 6410),
            array('id' => 13,'isim' => 'Gazimagosa', 'state_id' => 6410),
            array('id' => 14,'isim' => 'Güzelyurt', 'state_id' => 6410),
            array('id' => 15,'isim' => 'Pozanti', 'state_id' => 6410),
            array('id' => 16,'isim' => 'Saimbeyli', 'state_id' => 6410),
            array('id' => 17,'isim' => 'Sariçam','state_id' => 6410),
            array('id' => 18,'isim' => 'Yüregir','state_id' => 6410),
            array('id' => 19,'isim' => 'Gölbasi','state_id' => 6411),
            array('id' => 20,'isim' => 'Tut', 'state_id' => 6411),
            array('id' => 21,'isim' => 'Besni', 'state_id' => 6411),
            array('id' => 22,'isim' => 'Çelikhan', 'state_id' => 6411),
            array('id' => 23,'isim' => 'Gerger','state_id' => 6411),
            array('id' => 24,'isim' => 'Samsat','state_id' => 6411),
            array('id' => 25,'isim' => 'Kahta', 'state_id' =>6411),
            array('id' => 26, 'isim' => 'Merkez','state_id' => 6411),
            array('id' => 27, 'isim' => 'Sincik','state_id' => 6411),
            array('id' => 28, 'isim' => 'Eleskirt', 'state_id' => 6413),
            array('id' => 29, 'isim' => 'Hamur', 'state_id' =>6413),
            array('id' => 30, 'isim' => 'Patnos','state_id' => 6413),
            array('id' => 31, 'isim' => 'Diyadin', 'state_id' => 6413),
            array('id' => 32, 'isim' => 'Tutak', 'state_id' => 6413),
            array('id' => 33, 'isim' => 'Merkez', 'state_id' => 6413),
            array('id' => 34, 'isim' => 'Tasliçay', 'state_id' => 6413),
            array('id' => 35, 'isim' => 'Dogubayazit(Dogubeyazit)', 'state_id' => 6413),
            array('id' => 36, 'isim' => 'Gümüshaciköy', 'state_id' => 6414),
            array('id' => 37, 'isim' => 'Merzifon','state_id' => 6414),
            array('id' => 38, 'isim' => 'Hamamözü','state_id' => 6414),
            array('id' => 39, 'isim' => 'Göynücek','state_id' => 6414),
            array('id' => 40, 'isim' => 'Merkez', 'state_id' =>6414),
            array('id' => 41, 'isim' => 'Suluova','state_id' => 6414),
            array('id' => 42, 'isim' => 'Tasova', 'state_id' =>6414),
            array('id' => 43, 'isim' => 'Evren','state_id' => 6415),
            array('id' => 44, 'isim' => 'Güdül','state_id' => 6415),
            array('id' => 45, 'isim' => 'Kazan','state_id' => 6415),
            array('id' => 46, 'isim' => 'Pursaklar', 'state_id' => 6415),
            array('id' => 47, 'isim' => 'Çubuk', 'state_id' => 6415),
            array('id' => 48, 'isim' => 'Etimesgut','state_id' => 6415),
            array('id' => 49, 'isim' => 'Gölbasi', 'state_id' =>6415),
            array('id' => 50, 'isim' => 'Haymana', 'state_id' => 6415),
            array('id' => 51, 'isim' => 'Mamak', 'state_id' => 6415),
            array('id' => 52, 'isim' => 'Polatli', 'state_id' => 6415),
            array('id' => 53, 'isim' => 'Akyurt', 'state_id' => 6415),
            array('id' => 54, 'isim' => 'Ayas', 'state_id' => 6415),
            array('id' => 55, 'isim' => 'Çankaya', 'state_id' => 6415),
            array('id' => 56, 'isim' => 'Elmadag', 'state_id' => 6415),
            array('id' => 57, 'isim' => 'Nallihan', 'state_id' => 6415),
            array('id' => 58, 'isim' => 'Sincan', 'state_id' => 6415),
            array('id' => 59, 'isim' => 'Altindag', 'state_id' => 6415),
            array('id' => 60, 'isim' => 'Bala', 'state_id' => 6415),
            array('id' => 61, 'isim' => 'Beypazari', 'state_id' => 6415),
            array('id' => 62, 'isim' => 'Çamlidere', 'state_id' => 6415),
            array('id' => 63, 'isim' => 'Kalecik', 'state_id' => 6415),
            array('id' => 64, 'isim' => 'Keçiören', 'state_id' => 6415),
            array('id' => 65, 'isim' => 'Kizilcahamam', 'state_id' => 6415),
            array('id' => 66, 'isim' => 'Sereflikoçhisar', 'state_id' => 6415),
            array('id' => 67, 'isim' => 'Yenimahalle', 'state_id' => 6415),
            array('id' => 68, 'isim' => 'Aksu', 'state_id' => 6416),
            array('id' => 69, 'isim' => 'Demre(Kale)', 'state_id' => 6416),
            array('id' => 70, 'isim' => 'Gazipasa', 'state_id' => 6416),
            array('id' => 71, 'isim' => 'Kas', 'state_id' => 6416),
            array('id' => 72, 'isim' => 'Konyaalti', 'state_id' => 6416),
            array('id' => 73, 'isim' => 'Muratpasa', 'state_id' => 6416),
            array('id' => 74, 'isim' => 'Dösemealti', 'state_id' => 6416),
            array('id' => 75, 'isim' => 'Finike', 'state_id' => 6416),
            array('id' => 76, 'isim' => 'Manavgat', 'state_id' => 6416),
            array('id' => 77, 'isim' => 'Akseki', 'state_id' => 6416),
            array('id' => 78, 'isim' => 'Alanya', 'state_id' => 6416),
            array('id' => 79, 'isim' => 'Ibradi(Aydinkent)', 'state_id' => 6416),
            array('id' => 80, 'isim' => 'Kepez', 'state_id' => 6416),
            array('id' => 81, 'isim' => 'Korkuteli', 'state_id' => 6416),
            array('id' => 82, 'isim' => 'Kumluca', 'state_id' => 6416),
            array('id' => 83, 'isim' => 'Serik', 'state_id' => 6416),
            array('id' => 84, 'isim' => 'Elmali', 'state_id' => 6416),
            array('id' => 85, 'isim' => 'Gündogmus', 'state_id' => 6416),
            array('id' => 86, 'isim' => 'Kemer', 'state_id' => 6416),
            array('id' => 87, 'isim' => 'Arhavi', 'state_id' => 6417),
            array('id' => 88, 'isim' => 'Borçka', 'state_id' => 6417),
            array('id' => 89, 'isim' => 'Hopa', 'state_id' => 6417),
            array('id' => 90, 'isim' => 'Murgul(Göktas)', 'state_id' => 6417),
            array('id' => 91, 'isim' => 'Yusufeli', 'state_id' => 6417),
            array('id' => 92, 'isim' => 'Ardanuç', 'state_id' => 6417),
            array('id' => 93, 'isim' => 'Merkez', 'state_id' => 6417),
            array('id' => 94, 'isim' => 'Savsat', 'state_id' => 6417),
            array('id' => 95, 'isim' => 'Buharkent(Çubukdagi)', 'state_id' => 6418),
            array('id' => 96, 'isim' => 'Çine', 'state_id' => 6418),
            array('id' => 97, 'isim' => 'Incirliova', 'state_id' => 6418),
            array('id' => 98, 'isim' => 'Karacasu', 'state_id' => 6418),
            array('id' => 99, 'isim' => 'Karpuzlu', 'state_id' => 6418),
            array('id' => 100,'isim' => 'Kösk', 'state_id' => 6418),
            array('id' => 101,'isim' => 'Nazilli', 'state_id' => 6418),
            array('id' => 102,'isim' => 'Sultanhisar', 'state_id' => 6418),
            array('id' => 103,'isim' => 'Kusadasi', 'state_id' => 6418),
            array('id' => 104,'isim' => 'Merkez', 'state_id' => 6418),
            array('id' => 105,'isim' => 'Söke', 'state_id' => 6418),
            array('id' => 106, 'isim' => 'Yenipazar', 'state_id' => 6418),
            array('id' => 107, 'isim' => 'Bozdogan', 'state_id' => 6418),
            array('id' => 108, 'isim' => 'Germencik', 'state_id' => 6418),
            array('id' => 109, 'isim' => 'Kuyucak', 'state_id' => 6418),
            array('id' => 110, 'isim' => 'Didim(Yenihisar)', 'state_id' => 6418),
            array('id' => 111, 'isim' => 'Koçarli', 'state_id' => 6418),
            array('id' => 112, 'isim' => 'Ayvalik', 'state_id' => 6419),
            array('id' => 113, 'isim' => 'Balya', 'state_id' => 6419),
            array('id' => 114, 'isim' => 'Burhaniye', 'state_id' => 6419),
            array('id' => 115, 'isim' => 'Edremit', 'state_id' => 6419),
            array('id' => 116, 'isim' => 'Merkez', 'state_id' => 6419),
            array('id' => 117, 'isim' => 'Sindirgi', 'state_id' => 6419),
            array('id' => 118, 'isim' => 'Havran', 'state_id' => 6419),
            array('id' => 119, 'isim' => 'Kepsut', 'state_id' => 6419),
            array('id' => 120, 'isim' => 'Marmara', 'state_id' => 6419),
            array('id' => 121, 'isim' => 'Savastepe', 'state_id' => 6419),
            array('id' => 122, 'isim' => 'Bandirma', 'state_id' => 6419),
            array('id' => 123, 'isim' => 'Bigadiç', 'state_id' => 6419),
            array('id' => 124, 'isim' => 'Gömeç', 'state_id' => 6419),
            array('id' => 125, 'isim' => 'Dursunbey', 'state_id' => 6419),
            array('id' => 126, 'isim' => 'Erdek', 'state_id' => 6419),
            array('id' => 127, 'isim' => 'Gönen', 'state_id' => 6419),
            array('id' => 128, 'isim' => 'Ivrindi', 'state_id' => 6419),
            array('id' => 129, 'isim' => 'Manyas', 'state_id' => 6419),
            array('id' => 130, 'isim' => 'Susurluk', 'state_id' => 6419),
            array('id' => 131, 'isim' => 'Gölpazari', 'state_id' => 6420),
            array('id' => 132, 'isim' => 'Merkez', 'state_id' => 6420),
            array('id' => 133, 'isim' => 'Bozüyük', 'state_id' => 6420),
            array('id' => 134, 'isim' => 'Inhisar', 'state_id' => 6420),
            array('id' => 135, 'isim' => 'Pazaryeri', 'state_id' => 6420),
            array('id' => 136, 'isim' => 'Sögüt', 'state_id' => 6420),
            array('id' => 137, 'isim' => 'Yenipazar', 'state_id' => 6420),
            array('id' => 138, 'isim' => 'Osmaneli', 'state_id' => 6420),
            array('id' => 139, 'isim' => 'Adakli', 'state_id' => 6421),
            array('id' => 140, 'isim' => 'Merkez', 'state_id' => 6421),
            array('id' => 141, 'isim' => 'Yedisu', 'state_id' => 6421),
            array('id' => 142, 'isim' => 'Genç', 'state_id' => 6421),
            array('id' => 143, 'isim' => 'Yayladere', 'state_id' => 6421),
            array('id' => 144, 'isim' => 'Karliova', 'state_id' => 6421),
            array('id' => 145, 'isim' => 'Kigi', 'state_id' => 6421),
            array('id' => 146, 'isim' => 'Solhan', 'state_id' => 6421),
            array('id' => 147, 'isim' => 'Adilcevaz', 'state_id' => 6422),
            array('id' => 148, 'isim' => 'Merkez', 'state_id' => 6422),
            array('id' => 149, 'isim' => 'Güroymak', 'state_id' => 6422),
            array('id' => 150, 'isim' => 'Hizan','state_id' => 6422),
            array('id' => 151, 'isim' => 'Mutki','state_id' => 6422),
            array('id' => 152, 'isim' => 'Ahlat','state_id' => 6422),
            array('id' => 153, 'isim' => 'Tatvan', 'state_id' => 6422),
            array('id' => 154, 'isim' => 'Dörtdivan', 'state_id' => 6424),
            array('id' => 155, 'isim' => 'Merkez', 'state_id' =>6424),
            array('id' => 156, 'isim' => 'Göynük', 'state_id' =>6424),
            array('id' => 157, 'isim' => 'Kibriscik', 'state_id' => 6424),
            array('id' => 158, 'isim' => 'Mengen', 'state_id' => 6424),
            array('id' => 159, 'isim' => 'Mudurnu', 'state_id' => 6424),
            array('id' => 160, 'isim' => 'Gerede', 'state_id' => 6424),
            array('id' => 161, 'isim' => 'Seben', 'state_id' => 6424),
            array('id' => 162, 'isim' => 'Yeniçaga', 'state_id' => 6424),
            array('id' => 163, 'isim' => 'Altinyayla(Dirmil)', 'state_id' => 6425),
            array('id' => 164, 'isim' => 'Çavdir', 'state_id' => 6425),
            array('id' => 165, 'isim' => 'Kemer', 'state_id' => 6425),
            array('id' => 166, 'isim' => 'Aglasun', 'state_id' => 6425),
            array('id' => 167, 'isim' => 'Bucak', 'state_id' => 6425),
            array('id' => 168, 'isim' => 'Çeltikçi', 'state_id' => 6425),
            array('id' => 169, 'isim' => 'Yesilova', 'state_id' => 6425),
            array('id' => 170, 'isim' => 'Gölhisar', 'state_id' => 6425),
            array('id' => 171, 'isim' => 'Karamanli', 'state_id' => 6425),
            array('id' => 172, 'isim' => 'Merkez', 'state_id' => 6425),
            array('id' => 173, 'isim' => 'Tefenni', 'state_id' => 6425),
            array('id' => 174, 'isim' => 'Büyükorhan', 'state_id' => 6426),
            array('id' => 175, 'isim' => 'Gemlik', 'state_id' => 6426),
            array('id' => 176, 'isim' => 'Mustafakemalpasa', 'state_id' => 6426),
            array('id' => 177, 'isim' => 'Nilüfer', 'state_id' => 6426),
            array('id' => 178, 'isim' => 'Inegöl', 'state_id' => 6426),
            array('id' => 179, 'isim' => 'Keles', 'state_id' => 6426),
            array('id' => 180, 'isim' => 'Mudanya', 'state_id' => 6426),
            array('id' => 181, 'isim' => 'Orhaneli', 'state_id' => 6426),
            array('id' => 182, 'isim' => 'Orhangazi', 'state_id' => 6426),
            array('id' => 183, 'isim' => 'Yenisehir', 'state_id' => 6426),
            array('id' => 184, 'isim' => 'Yildirim', 'state_id' => 6426),
            array('id' => 185, 'isim' => 'Iznik', 'state_id' => 6426),
            array('id' => 186, 'isim' => 'Karacabey', 'state_id' => 6426),
            array('id' => 187, 'isim' => 'Osmangazi', 'state_id' => 6426),
            array('id' => 188, 'isim' => 'Gürsu', 'state_id' => 6426),
            array('id' => 189, 'isim' => 'Harmancik', 'state_id' => 6426),
            array('id' => 190, 'isim' => 'Kestel', 'state_id' => 6426),
            array('id' => 191, 'isim' => 'Bayramiç', 'state_id' => 6427),
            array('id' => 192, 'isim' => 'Eceabat', 'state_id' => 6427),
            array('id' => 193, 'isim' => 'Yenice', 'state_id' => 6427),
            array('id' => 194, 'isim' => 'Ayvacik', 'state_id' => 6427),
            array('id' => 195, 'isim' => 'Bozcaada', 'state_id' => 6427),
            array('id' => 196, 'isim' => 'Ezine', 'state_id' => 6427),
            array('id' => 197, 'isim' => 'Gelibolu', 'state_id' => 6427),
            array('id' => 198, 'isim' => 'Lapseki', 'state_id' => 6427),
            array('id' => 199, 'isim' => 'Biga', 'state_id' => 6427),
            array('id' => 200, 'isim' => 'Çan', 'state_id' => 6427),
            array('id' => 201, 'isim' => 'Gökçeada(Imroz)', 'state_id' => 6427),
            array('id' => 202, 'isim' => 'Merkez', 'state_id' => 6427),
            array('id' => 203, 'isim' => 'Atkaracalar', 'state_id' => 6428),
            array('id' => 204, 'isim' => 'Bayramören', 'state_id' => 6428),
            array('id' => 205, 'isim' => 'Çerkes', 'state_id' => 6428),
            array('id' => 206, 'isim' => 'Yaprakli', 'state_id' => 6428),
            array('id' => 207, 'isim' => 'Eldivan', 'state_id' => 6428),
            array('id' => 208, 'isim' => 'Ilgaz', 'state_id' => 6428),
            array('id' => 209, 'isim' => 'Merkez', 'state_id' => 6428),
            array('id' => 210, 'isim' => 'Kizilirmak', 'state_id' => 6428),
            array('id' => 211, 'isim' => 'Sabanözü', 'state_id' => 6428),
            array('id' => 212, 'isim' => 'Korgun', 'state_id' => 6428),
            array('id' => 213, 'isim' => 'Kursunlu', 'state_id' => 6428),
            array('id' => 214, 'isim' => 'Orta', 'state_id' => 6428),
            array('id' => 215, 'isim' => 'Bayat', 'state_id' => 6429),
            array('id' => 216, 'isim' => 'Iskilip', 'state_id' => 6429),
            array('id' => 217, 'isim' => 'Osmancik', 'state_id' => 6429),
            array('id' => 218, 'isim' => 'Ugurludag', 'state_id' => 6429),
            array('id' => 219, 'isim' => 'Dodurga', 'state_id' => 6429),
            array('id' => 220, 'isim' => 'Kargi', 'state_id' => 6429),
            array('id' => 221, 'isim' => 'Mecitözü', 'state_id' => 6429),
            array('id' => 222, 'isim' => 'Alaca', 'state_id' => 6429),
            array('id' => 223, 'isim' => 'Laçin', 'state_id' => 6429),
            array('id' => 224, 'isim' => 'Merkez', 'state_id' => 6429),
            array('id' => 225, 'isim' => 'Oguzlar(Karaören)', 'state_id' => 6429),
            array('id' => 226, 'isim' => 'Sungurlu', 'state_id' => 6429),
            array('id' => 227, 'isim' => 'Bogazkale', 'state_id' => 6429),
            array('id' => 228, 'isim' => 'Ortaköy', 'state_id' => 6429),
            array('id' => 229, 'isim' => 'Baklan', 'state_id' => 6430),
            array('id' => 230, 'isim' => 'Çal', 'state_id' => 6430),
            array('id' => 231, 'isim' => 'Güney', 'state_id' => 6430),
            array('id' => 232, 'isim' => 'Tavas', 'state_id' => 6430),
            array('id' => 233, 'isim' => 'Babadag', 'state_id' => 6430),
            array('id' => 234, 'isim' => 'Buldan', 'state_id' => 6430),
            array('id' => 235, 'isim' => 'Sarayköy', 'state_id' => 6430),
            array('id' => 236, 'isim' => 'Serinhisar', 'state_id' => 6430),
            array('id' => 237, 'isim' => 'Acipayam', 'state_id' => 6430),
            array('id' => 238, 'isim' => 'Beyagaç', 'state_id' => 6430),
            array('id' => 239, 'isim' => 'Çardak', 'state_id' => 6430),
            array('id' => 240, 'isim' => 'Honaz', 'state_id' => 6430),
            array('id' => 241, 'isim' => 'Merkez', 'state_id' => 6430),
            array('id' => 242, 'isim' => 'Akköy', 'state_id' => 6430),
            array('id' => 243, 'isim' => 'Bekilli', 'state_id' => 6430),
            array('id' => 244, 'isim' => 'Bozkurt', 'state_id' => 6430),
            array('id' => 245, 'isim' => 'Çameli', 'state_id' => 6430),
            array('id' => 246, 'isim' => 'Çivril', 'state_id' => 6430),
            array('id' => 247, 'isim' => 'Kale', 'state_id' => 6430),
            array('id' => 248, 'isim' => 'Çinar', 'state_id' => 6431),
            array('id' => 249, 'isim' => 'Çüngüs', 'state_id' => 6431),
            array('id' => 250, 'isim' => 'Dicle', 'state_id' => 6431),
            array('id' => 251, 'isim' => 'Lice', 'state_id' => 6431),
            array('id' => 252, 'isim' => 'Sur', 'state_id' => 6431),
            array('id' => 253, 'isim' => 'Yenisehir', 'state_id' => 6431),
            array('id' => 254, 'isim' => 'Bismil','state_id' => 6431),
            array('id' => 255, 'isim' => 'Silvan','state_id' => 6431),
            array('id' => 256, 'isim' => 'Çermik','state_id' => 6431),
            array('id' => 257, 'isim' => 'Egil', 'state_id' => 6431),
            array('id' => 258, 'isim' => 'Ergani', 'state_id' => 6431),
            array('id' => 259, 'isim' => 'Hazro', 'state_id' => 6431),
            array('id' => 260, 'isim' => 'Kayapinar', 'state_id' => 6431),
            array('id' => 261, 'isim' => 'Kulp', 'state_id' => 6431),
            array('id' => 262, 'isim' => 'Baglar', 'state_id' => 6431),
            array('id' => 263, 'isim' => 'Hani', 'state_id' => 6431),
            array('id' => 264, 'isim' => 'Kocaköy', 'state_id' => 6431),
            array('id' => 265, 'isim' => 'Kesan', 'state_id' => 6432),
            array('id' => 266, 'isim' => 'Süloglu(Süleoglu)', 'state_id' => 6432),
            array('id' => 267, 'isim' => 'Havsa', 'state_id' =>6432),
            array('id' => 268, 'isim' => 'Ipsala','state_id' => 6432),
            array('id' => 269, 'isim' => 'Meriç', 'state_id' =>6432),
            array('id' => 270, 'isim' => 'Merkez','state_id' => 6432),
            array('id' => 271, 'isim' => 'Uzunköprü','state_id' => 6432),
            array('id' => 272, 'isim' => 'Enez', 'state_id' => 6432),
            array('id' => 273, 'isim' => 'Lalapasa', 'state_id' => 6432),
            array('id' => 274, 'isim' => 'Alacakaya', 'state_id' => 6433),
            array('id' => 275, 'isim' => 'Kovancilar', 'state_id' => 6433),
            array('id' => 276, 'isim' => 'Baskil', 'state_id' => 6433),
            array('id' => 277, 'isim' => 'Merkez', 'state_id' => 6433),
            array('id' => 278, 'isim' => 'Palu', 'state_id' => 6433),
            array('id' => 279, 'isim' => 'Sivrice', 'state_id' => 6433),
            array('id' => 280, 'isim' => 'Agin', 'state_id' => 6433),
            array('id' => 281, 'isim' => 'Aricak', 'state_id' => 6433),
            array('id' => 282, 'isim' => 'Karakoçan', 'state_id' => 6433),
            array('id' => 283, 'isim' => 'Keban', 'state_id' => 6433),
            array('id' => 284, 'isim' => 'Maden', 'state_id' => 6433),
            array('id' => 285, 'isim' => 'Kemaliye', 'state_id' => 6434),
            array('id' => 286, 'isim' => 'Üzümlü', 'state_id' => 6434),
            array('id' => 287, 'isim' => 'Çayirli', 'state_id' => 6434),
            array('id' => 288, 'isim' => 'Kemah', 'state_id' => 6434),
            array('id' => 289, 'isim' => 'Tercan', 'state_id' => 6434),
            array('id' => 290, 'isim' => 'Iliç(Iliç)', 'state_id' => 6434),
            array('id' => 291, 'isim' => 'Merkez', 'state_id' => 6434),
            array('id' => 292, 'isim' => 'Otlukbeli', 'state_id' => 6434),
            array('id' => 293, 'isim' => 'Refahiye', 'state_id' => 6434),
            array('id' => 294, 'isim' => 'Karaçoban', 'state_id' => 6435),
            array('id' => 295, 'isim' => 'Narman', 'state_id' => 6435),
            array('id' => 296, 'isim' => 'Oltu', 'state_id' => 6435),
            array('id' => 297, 'isim' => 'Olur', 'state_id' => 6435),
            array('id' => 298, 'isim' => 'Tekman', 'state_id' => 6435),
            array('id' => 299, 'isim' => 'Tortum', 'state_id' => 6435),
            array('id' => 300, 'isim' => 'Uzundere', 'state_id' => 6435),
            array('id' => 301, 'isim' => 'Horasan', 'state_id' => 6435),
            array('id' => 302, 'isim' => 'Ispir', 'state_id' => 6435),
            array('id' => 303, 'isim' => 'Pasinler', 'state_id' => 6435),
            array('id' => 304, 'isim' => 'Senkaya', 'state_id' => 6435),
            array('id' => 305, 'isim' => 'Askale', 'state_id' => 6435),
            array('id' => 306, 'isim' => 'Aziziye(Ilica)', 'state_id' => 6435),
            array('id' => 307, 'isim' => 'Çat', 'state_id' => 6435),
            array('id' => 308, 'isim' => 'Karayazi', 'state_id' => 6435),
            array('id' => 309, 'isim' => 'Köprüköy', 'state_id' => 6435),
            array('id' => 310, 'isim' => 'Palandöken', 'state_id' => 6435),
            array('id' => 311, 'isim' => 'Yakutiye', 'state_id' => 6435),
            array('id' => 312, 'isim' => 'Hinis', 'state_id' => 6435),
            array('id' => 313, 'isim' => 'Pazaryolu', 'state_id' => 6435),
            array('id' => 314, 'isim' => 'Çifteler', 'state_id' => 6436),
            array('id' => 315, 'isim' => 'Han', 'state_id' => 6436),
            array('id' => 316, 'isim' => 'Mihalgazi','state_id' => 6436),
            array('id' => 317, 'isim' => 'Mihaliççik', 'state_id' => 6436),
            array('id' => 318, 'isim' => 'Tepebasi', 'state_id' => 6436),
            array('id' => 319, 'isim' => 'Alpu', 'state_id' => 6436),
            array('id' => 320, 'isim' => 'Günyüzü', 'state_id' => 6436),
            array('id' => 321, 'isim' => 'Saricakaya', 'state_id' => 6436),
            array('id' => 322, 'isim' => 'Beylikova', 'state_id' => 6436),
            array('id' => 323, 'isim' => 'Inönü', 'state_id' => 6436),
            array('id' => 324, 'isim' => 'Mahmudiye', 'state_id' => 6436),
            array('id' => 325, 'isim' => 'Odunpazari', 'state_id' => 6436),
            array('id' => 326, 'isim' => 'Seyitgazi', 'state_id' => 6436),
            array('id' => 327, 'isim' => 'Sivrihisar', 'state_id' => 6436),
            array('id' => 328, 'isim' => 'Islahiye', 'state_id' => 6437),
            array('id' => 329, 'isim' => 'Yavuzeli', 'state_id' => 6437),
            array('id' => 330, 'isim' => 'Karkamis', 'state_id' => 6437),
            array('id' => 331, 'isim' => 'Nizip', 'state_id' => 6437),
            array('id' => 332, 'isim' => 'Oguzeli', 'state_id' => 6437),
            array('id' => 333, 'isim' => 'Sahinbey', 'state_id' => 6437),
            array('id' => 334, 'isim' => 'Nurdagi', 'state_id' => 6437),
            array('id' => 335, 'isim' => 'Araban', 'state_id' => 6437),
            array('id' => 336, 'isim' => 'Sehitkamil', 'state_id' => 6437),
            array('id' => 337, 'isim' => 'Alucra', 'state_id' => 6438),
            array('id' => 338, 'isim' => 'Bulancak', 'state_id' => 6438),
            array('id' => 339, 'isim' => 'Çanakçi', 'state_id' => 6438),
            array('id' => 340, 'isim' => 'Merkez', 'state_id' => 6438),
            array('id' => 341, 'isim' => 'Yaglidere', 'state_id' => 6438),
            array('id' => 342, 'isim' => 'Dereli', 'state_id' => 6438),
            array('id' => 343, 'isim' => 'Eynesil', 'state_id' => 6438),
            array('id' => 344, 'isim' => 'Güce', 'state_id' => 6438),
            array('id' => 345, 'isim' => 'Kesap', 'state_id' => 6438),
            array('id' => 346, 'isim' => 'Dogankent', 'state_id' => 6438),
            array('id' => 347, 'isim' => 'Görele', 'state_id' => 6438),
            array('id' => 348, 'isim' => 'Çamoluk', 'state_id' => 6438),
            array('id' => 349, 'isim' => 'Espiye', 'state_id' => 6438),
            array('id' => 350, 'isim' => 'Piraziz', 'state_id' => 6438),
            array('id' => 351, 'isim' => 'Sebinkarahisar', 'state_id' => 6438),
            array('id' => 352, 'isim' => 'Tirebolu', 'state_id' => 6438),
            array('id' => 353, 'isim' => 'Merkez', 'state_id' => 6439),
            array('id' => 354, 'isim' => 'Torul', 'state_id' => 6439),
            array('id' => 355, 'isim' => 'Köse', 'state_id' => 6439),
            array('id' => 356, 'isim' => 'Kürtün', 'state_id' => 6439),
            array('id' => 357, 'isim' => 'Kelkit', 'state_id' => 6439),
            array('id' => 358, 'isim' => 'Siran', 'state_id' => 6439),
            array('id' => 359, 'isim' => 'Çukurca', 'state_id' => 6440),
            array('id' => 360, 'isim' => 'Merkez', 'state_id' => 6440),
            array('id' => 361, 'isim' => 'Yüksekova', 'state_id' => 6440),
            array('id' => 362, 'isim' => 'Semdinli', 'state_id' => 6440),
            array('id' => 363, 'isim' => 'Iskenderun', 'state_id' => 6441),
            array('id' => 364, 'isim' => 'Kumlu', 'state_id' => 6441),
            array('id' => 365, 'isim' => 'Dörtyol', 'state_id' => 6441),
            array('id' => 366, 'isim' => 'Hassa', 'state_id' => 6441),
            array('id' => 367, 'isim' => 'Reyhanli', 'state_id' => 6441),
            array('id' => 368, 'isim' => 'Samandag', 'state_id' =>6441),
            array('id' => 369, 'isim' => 'Yayladagi','state_id' => 6441),
            array('id' => 370, 'isim' => 'Altinözü', 'state_id' =>6441),
            array('id' => 371, 'isim' => 'Antakya', 'state_id' => 6441),
            array('id' => 372, 'isim' => 'Belen','state_id' => 6441),
            array('id' => 373, 'isim' => 'Erzin','state_id' => 6441),
            array('id' => 374, 'isim' => 'Kirikhan', 'state_id' => 6441),
            array('id' => 375, 'isim' => 'Atabey', 'state_id' => 6442),
            array('id' => 376, 'isim' => 'Sütçüler', 'state_id' => 6442),
            array('id' => 377, 'isim' => 'Uluborlu', 'state_id' => 6442),
            array('id' => 378, 'isim' => 'Gönen', 'state_id' =>6442),
            array('id' => 379, 'isim' => 'Merkez','state_id' => 6442),
            array('id' => 380, 'isim' => 'Aksu', 'state_id' => 6442),
            array('id' => 381, 'isim' => 'Egirdir(Egridir)', 'state_id' => 6442),
            array('id' => 382, 'isim' => 'Gelendost','state_id' => 6442),
            array('id' => 383, 'isim' => 'Keçiborlu','state_id' => 6442),
            array('id' => 384, 'isim' => 'Senirkent','state_id' => 6442),
            array('id' => 385, 'isim' => 'Sarkikaraagaç', 'state_id' => 6442),
            array('id' => 386, 'isim' => 'Yalvaç', 'state_id' => 6442),
            array('id' => 387, 'isim' => 'Yenisarbademli', 'state_id' => 6442),
            array('id' => 388, 'isim' => 'Adalar', 'state_id' => 6444),
            array('id' => 389, 'isim' => 'Avcilar', 'state_id' => 6444),
            array('id' => 390, 'isim' => 'Beykoz', 'state_id' => 6444),
            array('id' => 391, 'isim' => 'Çatalca', 'state_id' => 6444),
            array('id' => 392, 'isim' => 'Esenler', 'state_id' => 6444),
            array('id' => 393, 'isim' => 'Eyüp', 'state_id' => 6444),
            array('id' => 394, 'isim' => 'Fatih', 'state_id' => 6444),
            array('id' => 395, 'isim' => 'Gaziosmanpasa', 'state_id' => 6444),
            array('id' => 396, 'isim' => 'Kagithane', 'state_id' => 6444),
            array('id' => 397, 'isim' => 'Kartal', 'state_id' => 6444),
            array('id' => 398, 'isim' => 'Pendik', 'state_id' => 6444),
            array('id' => 399, 'isim' => 'Sariyer', 'state_id' => 6444),
            array('id' => 400, 'isim' => 'Sultangazi', 'state_id' => 6444),
            array('id' => 401, 'isim' => 'Tuzla', 'state_id' => 6444),
            array('id' => 402, 'isim' => 'Zeytinburnu', 'state_id' => 6444),
            array('id' => 403, 'isim' => 'Arnavutköy', 'state_id' => 6444),
            array('id' => 404, 'isim' => 'Bagcilar', 'state_id' => 6444),
            array('id' => 405, 'isim' => 'Bayrampasa', 'state_id' => 6444),
            array('id' => 406, 'isim' => 'Esenyurt', 'state_id' => 6444),
            array('id' => 407, 'isim' => 'Maltepe', 'state_id' => 6444),
            array('id' => 408, 'isim' => 'Silivri', 'state_id' => 6444),
            array('id' => 409, 'isim' => 'Sisli', 'state_id' => 6444),
            array('id' => 410, 'isim' => 'Üsküdar', 'state_id' => 6444),
            array('id' => 411, 'isim' => 'Bakirköy', 'state_id' => 6444),
            array('id' => 412, 'isim' => 'Basaksehir', 'state_id' => 6444),
            array('id' => 413, 'isim' => 'Besiktas', 'state_id' => 6444),
            array('id' => 414, 'isim' => 'Beylikdüzü', 'state_id' => 6444),
            array('id' => 415, 'isim' => 'Büyükçekmece', 'state_id' => 6444),
            array('id' => 416, 'isim' => 'Kadiköy', 'state_id' => 6444),
            array('id' => 417, 'isim' => 'Sancaktepe', 'state_id' => 6444),
            array('id' => 418, 'isim' => 'Sultanbeyli', 'state_id' => 6444),
            array('id' => 419, 'isim' => 'Atasehir', 'state_id' => 6444),
            array('id' => 420, 'isim' => 'Bahçelievler', 'state_id' => 6444),
            array('id' => 421, 'isim' => 'Beyoglu', 'state_id' => 6444),
            array('id' => 422, 'isim' => 'Çekmeköy', 'state_id' => 6444),
            array('id' => 423, 'isim' => 'Güngören', 'state_id' => 6444),
            array('id' => 424, 'isim' => 'Küçükçekmece', 'state_id' => 6444),
            array('id' => 425, 'isim' => 'Sile', 'state_id' => 6444),
            array('id' => 426, 'isim' => 'Ümraniye', 'state_id' => 6444),
            array('id' => 427, 'isim' => 'Balçova', 'state_id' => 6445),
            array('id' => 428, 'isim' => 'Bayindir', 'state_id' => 6445),
            array('id' => 429, 'isim' => 'Çigli', 'state_id' => 6445),
           array('id' => 430, 'isim' => 'Güzelbahçe', 'state_id' =>6445),
            array('id' => 431, 'isim' => 'Karabaglar','state_id' => 6445),
            array('id' => 432, 'isim' => 'Karaburun', 'state_id' =>6445),
            array('id' => 433, 'isim' => 'Kemalpasa', 'state_id' =>6445),
            array('id' => 434, 'isim' => 'Konak', 'state_id' =>6445),
            array('id' => 435, 'isim' => 'Ödemis','state_id' => 6445),
            array('id' => 436, 'isim' => 'Tire', 'state_id' => 6445),
            array('id' => 437, 'isim' => 'Bayrakli', 'state_id' => 6445),
            array('id' => 438, 'isim' => 'Dikili', 'state_id' => 6445),
            array('id' => 439, 'isim' => 'Seferihisar', 'state_id' => 6445),
            array('id' => 440, 'isim' => 'Aliaga','state_id' => 6445),
            array('id' => 441, 'isim' => 'Beydag','state_id' => 6445),
            array('id' => 442, 'isim' => 'Buca', 'state_id' =>6445),
            array('id' => 443, 'isim' => 'Çesme','state_id' => 6445),
            array('id' => 444, 'isim' => 'Foça', 'state_id' => 6445),
            array('id' => 445, 'isim' => 'Gaziemir', 'state_id' => 6445),
            array('id' => 446, 'isim' => 'Kinik','state_id' => 6445),
            array('id' => 447, 'isim' => 'Kiraz','state_id' => 6445),
            array('id' => 448, 'isim' => 'Torbali', 'state_id' => 6445),
            array('id' => 449, 'isim' => 'Urla', 'state_id' => 6445),
            array('id' => 450, 'isim' => 'Bergama','state_id' => 6445),
            array('id' => 451, 'isim' => 'Bornova','state_id' => 6445),
            array('id' => 452, 'isim' => 'Karsiyaka', 'state_id' => 6445),
            array('id' => 453, 'isim' => 'Menderes(Cumaovasi)', 'state_id' => 6445),
            array('id' => 454, 'isim' => 'Menemen', 'state_id' => 6445),
            array('id' => 455, 'isim' => 'Narlidere', 'state_id' => 6445),
            array('id' => 456, 'isim' => 'Selçuk', 'state_id' =>6445),
            array('id' => 457, 'isim' => 'Arpaçay','state_id' => 6446),
            array('id' => 458, 'isim' => 'Kagizman', 'state_id' => 6446),
            array('id' => 459, 'isim' => 'Susuz', 'state_id' =>6446),
            array('id' => 460, 'isim' => 'Merkez','state_id' => 6446),
            array('id' => 461, 'isim' => 'Akyaka','state_id' => 6446),
            array('id' => 462, 'isim' => 'Digor', 'state_id' =>6446),
           array('id' => 463, 'isim' => 'Sarikamis', 'state_id' => 6446),
            array('id' => 464, 'isim' => 'Selim', 'state_id' => 6446),
            array('id' => 465, 'isim' => 'Azdavay', 'state_id' => 6447),
            array('id' => 466, 'isim' => 'Hanönü(Gökçeagaç)', 'state_id' => 6447),
            array('id' => 467, 'isim' => 'Inebolu', 'state_id' => 6447),
            array('id' => 468, 'isim' => 'Araç', 'state_id' => 6447),
            array('id' => 469, 'isim' => 'Bozkurt', 'state_id' => 6447),
            array('id' => 470, 'isim' => 'Cide', 'state_id' => 6447),
            array('id' => 471, 'isim' => 'Çatalzeytin', 'state_id' => 6447),
            array('id' => 472, 'isim' => 'Daday', 'state_id' => 6447),
            array('id' => 473, 'isim' => 'Devrekani', 'state_id' => 6447),
            array('id' => 474, 'isim' => 'Doganyurt', 'state_id' => 6447),
            array('id' => 475, 'isim' => 'Ihsangazi', 'state_id' => 6447),
            array('id' => 476, 'isim' => 'Küre', 'state_id' => 6447),
            array('id' => 477, 'isim' => 'Seydiler', 'state_id' => 6447),
            array('id' => 478, 'isim' => 'Tasköprü', 'state_id' => 6447),
            array('id' => 479, 'isim' => 'Abana', 'state_id' => 6447),
            array('id' => 480, 'isim' => 'Agli', 'state_id' => 6447),
            array('id' => 481, 'isim' => 'Merkez', 'state_id' => 6447),
            array('id' => 482, 'isim' => 'Pinarbasi', 'state_id' => 6447),
            array('id' => 483, 'isim' => 'Tosya', 'state_id' => 6447),
            array('id' => 484, 'isim' => 'Senpazar', 'state_id' => 6447),
            array('id' => 485, 'isim' => 'Hacilar', 'state_id' =>6448),
            array('id' => 486, 'isim' => 'Akkisla', 'state_id' =>6448),
            array('id' => 487, 'isim' => 'Bünyan', 'state_id' =>6448),
            array('id' => 488, 'isim' => 'Tomarza','state_id' => 6448),
            array('id' => 489, 'isim' => 'Yahyali','state_id' => 6448),
            array('id' => 490, 'isim' => 'Felahiye', 'state_id' => 6448),
            array('id' => 491, 'isim' => 'Incesu', 'state_id' => 6448),
            array('id' => 492, 'isim' => 'Kocasinan','state_id' => 6448),
            array('id' => 493, 'isim' => 'Pinarbasi','state_id' => 6448),
            array('id' => 494, 'isim' => 'Sariz', 'state_id' =>6448),
            array('id' => 495, 'isim' => 'Talas', 'state_id' =>6448),
            array('id' => 496, 'isim' => 'Develi','state_id' => 6448),
            array('id' => 497, 'isim' => 'Melikgazi', 'state_id' => 6448),
            array('id' => 498, 'isim' => 'Özvatan(Çukur)', 'state_id' => 6448),
            array('id' => 499, 'isim' => 'Sarioglan','state_id' => 6448),
            array('id' => 500, 'isim' => 'Yesilhisar', 'state_id' => 6448),
            array('id' => 501, 'isim' => 'Demirköy', 'state_id' =>6449),
            array('id' => 502, 'isim' => 'Kofçaz','state_id' => 6449),
            array('id' => 503, 'isim' => 'Pehlivanköy','state_id' => 6449),
            array('id' => 504, 'isim' => 'Vize', 'state_id' => 6449),
            array('id' => 505, 'isim' => 'Lüleburgaz','state_id' => 6449),
            array('id' => 506, 'isim' => 'Babaeski', 'state_id' => 6449),
            array('id' => 507, 'isim' => 'Merkez', 'state_id' => 6449),
            array('id' => 508, 'isim' => 'Pinarhisar','state_id' => 6449),
            array('id' => 509, 'isim' => 'Akpinar','state_id' => 6450),
            array('id' => 510, 'isim' => 'Boztepe','state_id' => 6450),
            array('id' => 511, 'isim' => 'Kaman', 'state_id' =>6450),
            array('id' => 512, 'isim' => 'Mucur', 'state_id' =>6450),
            array('id' => 513, 'isim' => 'Akçakent','state_id' => 6450),
            array('id' => 514, 'isim' => 'Çiçekdagi','state_id' => 6450),
            array('id' => 515, 'isim' => 'Merkez', 'state_id' => 6450),
            array('id' => 516, 'isim' => 'Dilovasi', 'state_id' =>6452),
            array('id' => 517, 'isim' => 'Körfez(Tütünçiftlik)', 'state_id' => 6452),
            array('id' => 518, 'isim' => 'Darica', 'state_id' => 6452),
            array('id' => 519, 'isim' => 'Derince','state_id' => 6452),
            array('id' => 520, 'isim' => 'Gebze', 'state_id' => 6452),
            array('id' => 521, 'isim' => 'Karamürsel','state_id' => 6452),
            array('id' => 522, 'isim' => 'Basiskele', 'state_id' => 6452),
            array('id' => 523, 'isim' => 'Çayirova','state_id' => 6452),
            array('id' => 524, 'isim' => 'Gölcük', 'state_id' => 6452),
            array('id' => 525, 'isim' => 'Izmit', 'state_id' => 6452),
            array('id' => 526, 'isim' => 'Kandira', 'state_id' =>6452),
            array('id' => 527, 'isim' => 'Kartepe','state_id' => 6452),
            array('id' => 528, 'isim' => 'Akören','state_id' => 6453),
            array('id' => 529, 'isim' => 'Çumra', 'state_id' =>6453),
            array('id' => 530, 'isim' => 'Derbent','state_id' => 6453),
            array('id' => 531, 'isim' => 'Doganhisar', 'state_id' => 6453),
            array('id' => 532, 'isim' => 'Emirgazi', 'state_id' => 6453),
            array('id' => 533, 'isim' => 'Eregli', 'state_id' =>6453),
            array('id' => 534, 'isim' => 'Ilgin', 'state_id' => 6453),
            array('id' => 535, 'isim' => 'Sarayönü', 'state_id' => 6453),
            array('id' => 536, 'isim' => 'Bozkir','state_id' => 6453),
            array('id' => 537, 'isim' => 'Güneysinir','state_id' => 6453),
            array('id' => 538, 'isim' => 'Hadim','state_id' => 6453),
            array('id' => 539, 'isim' => 'Hüyük','state_id' => 6453),
            array('id' => 540, 'isim' => 'Seydisehir', 'state_id' => 6453),
            array('id' => 541, 'isim' => 'Yunak', 'state_id' => 6453),
            array('id' => 542, 'isim' => 'Aksehir', 'state_id' =>6453),
            array('id' => 543, 'isim' => 'Altinekin', 'state_id' => 6453),
            array('id' => 544, 'isim' => 'Cihanbeyli', 'state_id' => 6453),
            array('id' => 545, 'isim' => 'Çeltik', 'state_id' => 6453),
            array('id' => 546, 'isim' => 'Derebucak','state_id' => 6453),
            array('id' => 547, 'isim' => 'Kadinhani','state_id' => 6453),
            array('id' => 548, 'isim' => 'Karapinar','state_id' => 6453),
            array('id' => 549, 'isim' => 'Kulu', 'state_id' => 6453),
            array('id' => 550, 'isim' => 'Selçuklu', 'state_id' =>6453),
            array('id' => 551, 'isim' => 'Yalihüyük','state_id' => 6453),
            array('id' => 552, 'isim' => 'Ahirli', 'state_id' => 6453),
            array('id' => 553, 'isim' => 'Beysehir', 'state_id' => 6453),
            array('id' => 554, 'isim' => 'Halkapinar', 'state_id' => 6453),
            array('id' => 555, 'isim' => 'Karatay', 'state_id' => 6453),
            array('id' => 556, 'isim' => 'Meram', 'state_id' => 6453),
            array('id' => 557, 'isim' => 'Taskent', 'state_id' => 6453),
            array('id' => 558, 'isim' => 'Tuzlukçu', 'state_id' => 6453),
            array('id' => 559, 'isim' => 'Çavdarhisar', 'state_id' => 6454),
            array('id' => 560, 'isim' => 'Merkez', 'state_id' => 6454),
            array('id' => 561, 'isim' => 'Tavsanli', 'state_id' => 6454),
            array('id' => 562, 'isim' => 'Domaniç', 'state_id' => 6454),
            array('id' => 563, 'isim' => 'Dumlupinar', 'state_id' => 6454),
            array('id' => 564, 'isim' => 'Emet', 'state_id' => 6454),
            array('id' => 565, 'isim' => 'Gediz', 'state_id' => 6454),
            array('id' => 566, 'isim' => 'Hisarcik','state_id' => 6454),
            array('id' => 567, 'isim' => 'Pazarlar','state_id' => 6454),
            array('id' => 568, 'isim' => 'Saphane', 'state_id' =>6454),
            array('id' => 569, 'isim' => 'Altintas','state_id' => 6454),
            array('id' => 570, 'isim' => 'Aslanapa','state_id' => 6454),
            array('id' => 571, 'isim' => 'Simav', 'state_id' => 6454),
            array('id' => 572, 'isim' => 'Akçadag', 'state_id' => 6455),
            array('id' => 573, 'isim' => 'Dogansehir', 'state_id' => 6455),
            array('id' => 574, 'isim' => 'Kuluncak', 'state_id' => 6455),
            array('id' => 575, 'isim' => 'Merkez', 'state_id' => 6455),
            array('id' => 576, 'isim' => 'Arapkir(Arapgir)', 'state_id' => 6455),
            array('id' => 577, 'isim' => 'Battalgazi', 'state_id' => 6455),
            array('id' => 578, 'isim' => 'Hekimhan', 'state_id' => 6455),
            array('id' => 579, 'isim' => 'Yesilyurt', 'state_id' => 6455),
            array('id' => 580, 'isim' => 'Darende', 'state_id' => 6455),
            array('id' => 581, 'isim' => 'Pütürge(Pötürge)', 'state_id' => 6455),
            array('id' => 582, 'isim' => 'Yazihan','state_id' => 6455),
            array('id' => 583, 'isim' => 'Arguvan','state_id' => 6455),
            array('id' => 584, 'isim' => 'Doganyol','state_id' => 6455),
            array('id' => 585, 'isim' => 'Kale', 'state_id' => 6455),
            array('id' => 586, 'isim' => 'Gölmarmara', 'state_id' => 6456),
            array('id' => 587, 'isim' => 'Gördes', 'state_id' => 6456),
            array('id' => 588, 'isim' => 'Kula', 'state_id' => 6456),
            array('id' => 589, 'isim' => 'Merkez', 'state_id' =>6456),
            array('id' => 590, 'isim' => 'Sarigöl','state_id' => 6456),
            array('id' => 591, 'isim' => 'Selendi','state_id' => 6456),
            array('id' => 592, 'isim' => 'Soma', 'state_id' => 6456),
            array('id' => 593, 'isim' => 'Ahmetli','state_id' => 6456),
            array('id' => 594, 'isim' => 'Demirci','state_id' => 6456),
            array('id' => 595, 'isim' => 'Salihli','state_id' => 6456),
            array('id' => 596, 'isim' => 'Köprübasi', 'state_id' =>6456),
            array('id' => 597, 'isim' => 'Saruhanli', 'state_id' =>6456),
            array('id' => 598, 'isim' => 'Akhisar', 'state_id' => 6456),
            array('id' => 599, 'isim' => 'Alasehir','state_id' => 6456),
            array('id' => 600, 'isim' => 'Kirkagaç','state_id' => 6456),
            array('id' => 601, 'isim' => 'Turgutlu','state_id' => 6456),
            array('id' => 602, 'isim' => 'Dargeçit','state_id' => 6459),
            array('id' => 603, 'isim' => 'Derik', 'state_id' =>6459),
            array('id' => 604, 'isim' => 'Merkez','state_id' => 6459),
            array('id' => 605, 'isim' => 'Mazidagi', 'state_id' =>6459),
            array('id' => 606, 'isim' => 'Kiziltepe','state_id' => 6459),
            array('id' => 607, 'isim' => 'Midyat(Estel)', 'state_id' => 6459),
            array('id' => 608, 'isim' => 'Nusaybin', 'state_id' => 6459),
            array('id' => 609, 'isim' => 'Ömerli', 'state_id' => 6459),
            array('id' => 610, 'isim' => 'Savur', 'state_id' => 6459),
            array('id' => 611, 'isim' => 'Yesilli', 'state_id' =>6459),
            array('id' => 612, 'isim' => 'Köycegiz','state_id' => 6460),
            array('id' => 613, 'isim' => 'Milas', 'state_id' => 6460),
            array('id' => 614, 'isim' => 'Dalaman', 'state_id' =>6460),
            array('id' => 615, 'isim' => 'Datça', 'state_id' => 6460),
            array('id' => 616, 'isim' => 'Kavaklidere', 'state_id' => 6460),
            array('id' => 617, 'isim' => 'Marmaris', 'state_id' => 6460),
            array('id' => 618, 'isim' => 'Merkez', 'state_id' =>6460),
            array('id' => 619, 'isim' => 'Ortaca', 'state_id' =>6460),
            array('id' => 620, 'isim' => 'Bodrum', 'state_id' =>6460),
            array('id' => 621, 'isim' => 'Fethiye','state_id' => 6460),
            array('id' => 622, 'isim' => 'Ula', 'state_id' => 6460),
            array('id' => 623, 'isim' => 'Yatagan','state_id' => 6460),
            array('id' => 624, 'isim' => 'Hasköy','state_id' => 6461),
            array('id' => 625, 'isim' => 'Malazgirt','state_id' => 6461),
            array('id' => 626, 'isim' => 'Bulanik', 'state_id' =>6461),
            array('id' => 627, 'isim' => 'Varto', 'state_id' =>6461),
            array('id' => 628, 'isim' => 'Korkut','state_id' => 6461),
            array('id' => 629, 'isim' => 'Merkez','state_id' => 6461),
            array('id' => 630, 'isim' => 'Avanos','state_id' => 6462),
            array('id' => 631, 'isim' => 'Kozakli', 'state_id' => 6462),
            array('id' => 632, 'isim' => 'Derinkuyu', 'state_id' => 6462),
            array('id' => 633, 'isim' => 'Gülsehir', 'state_id' => 6462),
            array('id' => 634, 'isim' => 'Merkez', 'state_id' =>6462),
            array('id' => 635, 'isim' => 'Acigöl', 'state_id' =>6462),
            array('id' => 636, 'isim' => 'Hacibektas', 'state_id' => 6462),
            array('id' => 637, 'isim' => 'Ürgüp', 'state_id' => 6462),
            array('id' => 638, 'isim' => 'Çamardi', 'state_id' =>6463),
            array('id' => 639, 'isim' => 'Ulukisla','state_id' => 6463),
            array('id' => 640, 'isim' => 'Çiftlik(Özyurt)', 'state_id' => 6463),
            array('id' => 641, 'isim' => 'Altunhisar', 'state_id' => 6463),
            array('id' => 642, 'isim' => 'Bor', 'state_id' => 6463),
            array('id' => 643, 'isim' => 'Merkez', 'state_id' => 6463),
            array('id' => 644, 'isim' => 'Akkus', 'state_id' => 6464),
            array('id' => 645, 'isim' => 'Çatalpinar', 'state_id' => 6464),
            array('id' => 646, 'isim' => 'Çaybasi','state_id' => 6464),
            array('id' => 647, 'isim' => 'Gülyali','state_id' => 6464),
            array('id' => 648, 'isim' => 'Aybasti','state_id' => 6464),
            array('id' => 649, 'isim' => 'Fatsa','state_id' => 6464),
            array('id' => 650, 'isim' => 'Ikizce', 'state_id' => 6464),
            array('id' => 651, 'isim' => 'Kumru', 'state_id' =>6464),
            array('id' => 652, 'isim' => 'Ulubey','state_id' => 6464),
            array('id' => 653, 'isim' => 'Gölköy','state_id' => 6464),
            array('id' => 654, 'isim' => 'Gürgentepe', 'state_id' => 6464),
            array('id' => 655, 'isim' => 'Kabadüz(Karadüz)', 'state_id' => 6464),
            array('id' => 656, 'isim' => 'Korgan','state_id' => 6464),
            array('id' => 657, 'isim' => 'Merkez','state_id' => 6464),
            array('id' => 658, 'isim' => 'Mesudiye', 'state_id' => 6464),
            array('id' => 659, 'isim' => 'Ünye', 'state_id' => 6464),
            array('id' => 660, 'isim' => 'Çamas', 'state_id' => 6464),
            array('id' => 661, 'isim' => 'Kabatas', 'state_id' =>6464),
            array('id' => 662, 'isim' => 'Persembe','state_id' => 6464),
            array('id' => 663, 'isim' => 'Derepazari','state_id' => 6465),
            array('id' => 664, 'isim' => 'Çamlihemsin', 'state_id' =>6465),
            array('id' => 665, 'isim' => 'Ardesen', 'state_id' => 6465),
            array('id' => 666, 'isim' => 'Çayeli', 'state_id' => 6465),
            array('id' => 667, 'isim' => 'Findikli', 'state_id' => 6465),
            array('id' => 668, 'isim' => 'Hemsin', 'state_id' =>6465),
            array('id' => 669, 'isim' => 'Iyidere','state_id' => 6465),
            array('id' => 670, 'isim' => 'Kalkandere', 'state_id' => 6465),
            array('id' => 671, 'isim' => 'Merkez', 'state_id' =>6465),
            array('id' => 672, 'isim' => 'Güneysu','state_id' => 6465),
            array('id' => 673, 'isim' => 'Ikizdere', 'state_id' => 6465),
            array('id' => 674, 'isim' => 'Pazar', 'state_id' => 6465),
            array('id' => 675, 'isim' => 'Arifiye', 'state_id' => 6466),
            array('id' => 676, 'isim' => 'Hendek', 'state_id' =>6466),
            array('id' => 677, 'isim' => 'Karasu', 'state_id' =>6466),
            array('id' => 678, 'isim' => 'Kaynarca','state_id' => 6466),
            array('id' => 679, 'isim' => 'Sapanca', 'state_id' =>6466),
            array('id' => 680, 'isim' => 'Serdivan','state_id' => 6466),
            array('id' => 681, 'isim' => 'Akyazi', 'state_id' => 6466),
            array('id' => 682, 'isim' => 'Geyve', 'state_id' =>6466),
            array('id' => 683, 'isim' => 'Pamukova', 'state_id' => 6466),
            array('id' => 684, 'isim' => 'Karapürçek', 'state_id' => 6466),
            array('id' => 685, 'isim' => 'Sögütlü', 'state_id' => 6466),
            array('id' => 686, 'isim' => 'Adapazari', 'state_id' => 6466),
            array('id' => 687, 'isim' => 'Erenler','state_id' => 6466),
            array('id' => 688, 'isim' => 'Ferizli','state_id' => 6466),
            array('id' => 689, 'isim' => 'Kocaali','state_id' => 6466),
            array('id' => 690, 'isim' => 'Tarakli','state_id' => 6466),
            array('id' => 691, 'isim' => 'Canik', 'state_id' => 6467),
            array('id' => 692, 'isim' => 'Çarsamba', 'state_id' => 6467),
            array('id' => 693, 'isim' => 'Terme', 'state_id' => 6467),
            array('id' => 694, 'isim' => 'Vezirköprü', 'state_id' => 6467),
            array('id' => 695, 'isim' => 'Asarcik', 'state_id' => 6467),
            array('id' => 696, 'isim' => 'Havza', 'state_id' => 6467),
            array('id' => 697, 'isim' => 'Ilkadim', 'state_id' => 6467),
            array('id' => 698, 'isim' => 'Ondokuzmayis(Ballica)', 'state_id' => 6467),
            array('id' => 699, 'isim' => 'Salipazari', 'state_id' => 6467),
            array('id' => 700, 'isim' => 'Ayvacik', 'state_id' => 6467),
            array('id' => 701, 'isim' => 'Kavak', 'state_id' =>6467),
            array('id' => 702, 'isim' => 'Ladik', 'state_id' =>6467),
            array('id' => 703, 'isim' => 'Tekkeköy','state_id' => 6467),
            array('id' => 704, 'isim' => 'Yakakent','state_id' => 6467),
            array('id' => 705, 'isim' => 'Alaçam','state_id' => 6467),
            array('id' => 706, 'isim' => 'Atakum','state_id' => 6467),
            array('id' => 707, 'isim' => 'Bafra', 'state_id' =>6467),
            array('id' => 708, 'isim' => 'Aydinlar', 'state_id' => 6468),
            array('id' => 709, 'isim' => 'Baykan', 'state_id' =>6468),
            array('id' => 710, 'isim' => 'Pervari','state_id' => 6468),
            array('id' => 711, 'isim' => 'Sirvan', 'state_id' => 6468),
            array('id' => 712, 'isim' => 'Eruh', 'state_id' => 6468),
            array('id' => 713, 'isim' => 'Kurtalan', 'state_id' => 6468),
            array('id' => 714, 'isim' => 'Merkez', 'state_id' => 6468),
            array('id' => 715, 'isim' => 'Ayancik','state_id' => 6469),
            array('id' => 716, 'isim' => 'Boyabat','state_id' => 6469),
            array('id' => 717, 'isim' => 'Duragan','state_id' => 6469),
            array('id' => 718, 'isim' => 'Dikmen', 'state_id' =>6469),
            array('id' => 719, 'isim' => 'Erfelek','state_id' => 6469),
            array('id' => 720, 'isim' => 'Merkez', 'state_id' =>6469),
            array('id' => 721, 'isim' => 'Saraydüzü', 'state_id' => 6469),
            array('id' => 722, 'isim' => 'Türkeli', 'state_id' => 6469),
            array('id' => 723, 'isim' => 'Gerze', 'state_id' =>6469),
            array('id' => 724, 'isim' => 'Gürün', 'state_id' => 6470),
            array('id' => 725, 'isim' => 'Kangal', 'state_id' =>6470),
            array('id' => 726, 'isim' => 'Koyulhisar', 'state_id' => 6470),
            array('id' => 727, 'isim' => 'Gemerek', 'state_id' => 6470),
            array('id' => 728, 'isim' => 'Gölova', 'state_id' => 6470),
            array('id' => 729, 'isim' => 'Hafik', 'state_id' => 6470),
            array('id' => 730, 'isim' => 'Susehri', 'state_id' =>6470),
            array('id' => 731, 'isim' => 'Sarkisla','state_id' => 6470),
            array('id' => 732, 'isim' => 'Yildizeli','state_id' => 6470),
            array('id' => 733, 'isim' => 'Akincilar','state_id' => 6470),
            array('id' => 734, 'isim' => 'Altinyayla', 'state_id' => 6470),
            array('id' => 735, 'isim' => 'Divrigi', 'state_id' =>6470),
            array('id' => 736, 'isim' => 'Dogansar','state_id' => 6470),
            array('id' => 737, 'isim' => 'Imranli', 'state_id' =>6470),
            array('id' => 738, 'isim' => 'Ulas', 'state_id' => 6470),
            array('id' => 739, 'isim' => 'Merkez', 'state_id' => 6470),
            array('id' => 740, 'isim' => 'Zara', 'state_id' => 6470),
            array('id' => 741, 'isim' => 'Çorlu', 'state_id' => 6471),
            array('id' => 742, 'isim' => 'Merkez', 'state_id' => 6471),
            array('id' => 743, 'isim' => 'Sarköy', 'state_id' => 6471),
            array('id' => 744, 'isim' => 'Çerkezköy', 'state_id' => 6471),
            array('id' => 745, 'isim' => 'Marmaraereglisi', 'state_id' => 6471),
            array('id' => 746, 'isim' => 'Hayrabolu', 'state_id' => 6471),
            array('id' => 747, 'isim' => 'Malkara', 'state_id' => 6471),
            array('id' => 748, 'isim' => 'Muratli', 'state_id' => 6471),
            array('id' => 749, 'isim' => 'Saray', 'state_id' => 6471),
            array('id' => 750, 'isim' => 'Almus', 'state_id' => 6472),
            array('id' => 751, 'isim' => 'Merkez', 'state_id' => 6472),
            array('id' => 752, 'isim' => 'Pazar', 'state_id' => 6472),
            array('id' => 753, 'isim' => 'Resadiye', 'state_id' => 6472),
            array('id' => 754, 'isim' => 'Artova', 'state_id' => 6472),
            array('id' => 755, 'isim' => 'Erbaa', 'state_id' => 6472),
            array('id' => 756, 'isim' => 'Niksar', 'state_id' => 6472),
            array('id' => 757, 'isim' => 'Sulusaray', 'state_id' => 6472),
            array('id' => 758, 'isim' => 'Zile', 'state_id' => 6472),
            array('id' => 759, 'isim' => 'Basçiftlik', 'state_id' => 6472),
            array('id' => 760, 'isim' => 'Turhal', 'state_id' => 6472),
            array('id' => 761, 'isim' => 'Yesilyurt', 'state_id' => 6472),
            array('id' => 762, 'isim' => 'Besikdüzü', 'state_id' => 6473),
            array('id' => 763, 'isim' => 'Düzköy','state_id' => 6473),
            array('id' => 764, 'isim' => 'Merkez','state_id' => 6473),
            array('id' => 765, 'isim' => 'Tonya', 'state_id' => 6473),
            array('id' => 766, 'isim' => 'Çarsibasi', 'state_id' => 6473),
            array('id' => 767, 'isim' => 'Çaykara','state_id' => 6473),
            array('id' => 768, 'isim' => 'Sürmene','state_id' => 6473),
            array('id' => 769, 'isim' => 'Vakfikebir', 'state_id' => 6473),
            array('id' => 770, 'isim' => 'Akçaabat','state_id' => 6473),
            array('id' => 771, 'isim' => 'Arsin','state_id' => 6473),
            array('id' => 772, 'isim' => 'Dernekpazari', 'state_id' => 6473),
            array('id' => 773, 'isim' => 'Köprübasi', 'state_id' => 6473),
            array('id' => 774, 'isim' => 'Maçka', 'state_id' => 6473),
            array('id' => 775, 'isim' => 'Of', 'state_id' => 6473),
            array('id' => 776, 'isim' => 'Salpazari', 'state_id' => 6473),
            array('id' => 777, 'isim' => 'Yomra', 'state_id' => 6473),
            array('id' => 778, 'isim' => 'Arakli','state_id' => 6473),
            array('id' => 779, 'isim' => 'Hayrat','state_id' => 6473),
            array('id' => 780, 'isim' => 'Hozat', 'state_id' => 6474),
            array('id' => 781, 'isim' => 'Mazgirt', 'state_id' => 6474),
            array('id' => 782, 'isim' => 'Merkez', 'state_id' =>6474),
            array('id' => 783, 'isim' => 'Pülümür','state_id' => 6474),
            array('id' => 784, 'isim' => 'Çemisgezek', 'state_id' => 6474),
            array('id' => 785, 'isim' => 'Ovacik', 'state_id' => 6474),
            array('id' => 786, 'isim' => 'Nazimiye', 'state_id' => 6474),
            array('id' => 787, 'isim' => 'Pertek','state_id' => 6474),
            array('id' => 788, 'isim' => 'Merkez','state_id' => 6476),
            array('id' => 789, 'isim' => 'Esme', 'state_id' => 6476),
            array('id' => 790, 'isim' => 'Karahalli', 'state_id' =>6476),
            array('id' => 791, 'isim' => 'Ulubey','state_id' => 6476),
            array('id' => 792, 'isim' => 'Banaz', 'state_id' =>6476),
            array('id' => 793, 'isim' => 'Sivasli', 'state_id' => 6476),
            array('id' => 794, 'isim' => 'Çatak', 'state_id' => 6477),
            array('id' => 795, 'isim' => 'Edremit(Gümüsdere)', 'state_id' => 6477),
            array('id' => 796, 'isim' => 'Ercis','state_id' => 6477),
            array('id' => 797, 'isim' => 'Gevas','state_id' => 6477),
            array('id' => 798, 'isim' => 'Gürpinar', 'state_id' => 6477),
            array('id' => 799, 'isim' => 'Saray', 'state_id' => 6477),
            array('id' => 800, 'isim' => 'Muradiye', 'state_id' => 6477),
            array('id' => 801, 'isim' => 'Baskale', 'state_id' => 6477),
            array('id' => 802, 'isim' => 'Çaldiran', 'state_id' => 6477),
            array('id' => 803, 'isim' => 'Özalp', 'state_id' => 6477),
            array('id' => 804, 'isim' => 'Bahçesaray', 'state_id' => 6477),
            array('id' => 805, 'isim' => 'Merkez', 'state_id' => 6477),
            array('id' => 806, 'isim' => 'Akdagmadeni', 'state_id' => 6478),
            array('id' => 807, 'isim' => 'Kadisehri', 'state_id' => 6478),
            array('id' => 808, 'isim' => 'Merkez', 'state_id' => 6478),
            array('id' => 809, 'isim' => 'Sefaatli', 'state_id' => 6478),
            array('id' => 810, 'isim' => 'Yenifakili', 'state_id' => 6478),
            array('id' => 811, 'isim' => 'Bogazliyan', 'state_id' => 6478),
            array('id' => 812, 'isim' => 'Aydincik', 'state_id' => 6478),
            array('id' => 813, 'isim' => 'Sorgun', 'state_id' => 6478),
            array('id' => 814, 'isim' => 'Çandir', 'state_id' => 6478),
            array('id' => 815, 'isim' => 'Çayiralan', 'state_id' => 6478),
            array('id' => 816, 'isim' => 'Çekerek', 'state_id' => 6478),
            array('id' => 817, 'isim' => 'Saraykent', 'state_id' => 6478),
            array('id' => 818, 'isim' => 'Sarikaya', 'state_id' => 6478),
            array('id' => 819, 'isim' => 'Yerköy', 'state_id' => 6478),
            array('id' => 820, 'isim' => 'Gökçebey', 'state_id' => 6479),
            array('id' => 821, 'isim' => 'Devrek', 'state_id' => 6479),
            array('id' => 822, 'isim' => 'Karadenizeregli', 'state_id' => 6479),
            array('id' => 823, 'isim' => 'Çaycuma', 'state_id' => 6479),
            array('id' => 824, 'isim' => 'Alapli','state_id' => 6479),
            array('id' => 825, 'isim' => 'Merkez','state_id' => 6479),
            array('id' => 826, 'isim' => 'Agaçören','state_id' => 6480),
            array('id' => 827, 'isim' => 'Gülagaç', 'state_id' =>6480),
            array('id' => 828, 'isim' => 'Güzelyurt', 'state_id' => 6480),
            array('id' => 829, 'isim' => 'Merkez', 'state_id' => 6480),
            array('id' => 830, 'isim' => 'Ortaköy', 'state_id' => 6480),
            array('id' => 831, 'isim' => 'Eskil', 'state_id' => 6480),
            array('id' => 832, 'isim' => 'Sariyahsi', 'state_id' => 6480),
            array('id' => 833, 'isim' => 'Merkez', 'state_id' => 6481),
            array('id' => 834, 'isim' => 'Aydintepe', 'state_id' => 6481),
            array('id' => 835, 'isim' => 'Demirözü', 'state_id' => 6481),
            array('id' => 836, 'isim' => 'Ayranci', 'state_id' => 6482),
            array('id' => 837, 'isim' => 'Basyayla', 'state_id' => 6482),
            array('id' => 838, 'isim' => 'Ermenek', 'state_id' => 6482),
            array('id' => 839, 'isim' => 'Sariveliler', 'state_id' => 6482),
            array('id' => 840, 'isim' => 'Merkez', 'state_id' => 6482),
            array('id' => 841, 'isim' => 'Kazimkarabekir', 'state_id' => 6482),
            array('id' => 842, 'isim' => 'Delice', 'state_id' => 6483),
            array('id' => 843, 'isim' => 'Keskin', 'state_id' => 6483),
            array('id' => 844, 'isim' => 'Baliseyh', 'state_id' => 6483),
            array('id' => 845, 'isim' => 'Yahsihan', 'state_id' => 6483),
            array('id' => 846, 'isim' => 'Bahsili', 'state_id' => 6483),
            array('id' => 847, 'isim' => 'Çelebi', 'state_id' => 6483),
            array('id' => 848, 'isim' => 'Karakeçili', 'state_id' => 6483),
            array('id' => 849, 'isim' => 'Merkez', 'state_id' => 6483),
            array('id' => 850, 'isim' => 'Sulakyurt', 'state_id' => 6483),
            array('id' => 851, 'isim' => 'Besiri','state_id' => 6484),
            array('id' => 852, 'isim' => 'Kozluk','state_id' => 6484),
            array('id' => 853, 'isim' => 'Gercüs','state_id' => 6484),
            array('id' => 854, 'isim' => 'Merkez','state_id' => 6484),
            array('id' => 855, 'isim' => 'Hasankeyf', 'state_id' => 6484),
            array('id' => 856, 'isim' => 'Sason', 'state_id' => 6484),
            array('id' => 857, 'isim' => 'Cizre', 'state_id' => 6485),
            array('id' => 858, 'isim' => 'Merkez', 'state_id' => 6485),
            array('id' => 859, 'isim' => 'Beytüssebap', 'state_id' => 6485),
            array('id' => 860, 'isim' => 'Idil', 'state_id' => 6485),
            array('id' => 861, 'isim' => 'Uludere', 'state_id' => 6485),
            array('id' => 862, 'isim' => 'Güçlükonak', 'state_id' => 6485),
            array('id' => 863, 'isim' => 'Silopi', 'state_id' => 6485),
            array('id' => 864, 'isim' => 'Amasra', 'state_id' => 6486),
            array('id' => 865, 'isim' => 'Kurucasile', 'state_id' => 6486),
            array('id' => 866, 'isim' => 'Ulus', 'state_id' => 6486),
            array('id' => 867, 'isim' => 'Merkez', 'state_id' => 6486),
            array('id' => 868, 'isim' => 'Merkez', 'state_id' => 6487),
            array('id' => 869, 'isim' => 'Çildir', 'state_id' => 6487),
            array('id' => 870, 'isim' => 'Damal', 'state_id' => 6487),
            array('id' => 871, 'isim' => 'Hanak', 'state_id' => 6487),
            array('id' => 872, 'isim' => 'Posof', 'state_id' => 6487),
            array('id' => 873, 'isim' => 'Göle', 'state_id' => 6487),
            array('id' => 874, 'isim' => 'Aralik', 'state_id' => 6488),
            array('id' => 875, 'isim' => 'Tuzluca', 'state_id' => 6488),
            array('id' => 876, 'isim' => 'Karakoyunlu', 'state_id' => 6488),
            array('id' => 877, 'isim' => 'Merkez', 'state_id' => 6488),
            array('id' => 878, 'isim' => 'Armutlu', 'state_id' => 6489),
            array('id' => 879, 'isim' => 'Çinarcik', 'state_id' => 6489),
            array('id' => 880, 'isim' => 'Merkez', 'state_id' => 6489),
            array('id' => 881, 'isim' => 'Altinova', 'state_id' => 6489),
            array('id' => 882, 'isim' => 'Çiftlikköy', 'state_id' => 6489),
            array('id' => 883, 'isim' => 'Termal', 'state_id' => 6489),
            array('id' => 884, 'isim' => 'Ovacik','state_id' => 6490),
            array('id' => 885, 'isim' => 'Yenice','state_id' => 6490),
            array('id' => 886, 'isim' => 'Eflani','state_id' => 6490),
            array('id' => 887, 'isim' => 'Eskipazar', 'state_id' => 6490),
            array('id' => 888, 'isim' => 'Merkez', 'state_id' => 6490),
            array('id' => 889, 'isim' => 'Safranbolu', 'state_id' => 6490),
            array('id' => 890, 'isim' => 'Merkez', 'state_id' => 6491),
            array('id' => 891, 'isim' => 'Elbeyli','state_id' => 6491),
            array('id' => 892, 'isim' => 'Musabeyli', 'state_id' => 6491),
            array('id' => 893, 'isim' => 'Polateli', 'state_id' => 6491),
            array('id' => 894, 'isim' => 'Merkez', 'state_id' => 6492),
            array('id' => 895, 'isim' => 'Toprakkale', 'state_id' => 6492),
            array('id' => 896, 'isim' => 'Kadirli', 'state_id' => 6492),
            array('id' => 897, 'isim' => 'Bahçe', 'state_id' => 6492),
            array('id' => 898, 'isim' => 'Düziçi', 'state_id' => 6492),
            array('id' => 899, 'isim' => 'Hasanbeyli', 'state_id' => 6492),
            array('id' => 900, 'isim' => 'Sumbas', 'state_id' => 6492),
            array('id' => 901, 'isim' => 'Akçakoca','state_id' => 6493),
            array('id' => 902, 'isim' => 'Kaynasli','state_id' => 6493),
            array('id' => 903, 'isim' => 'Yigilca', 'state_id' =>6493),
            array('id' => 904, 'isim' => 'Cumayeri','state_id' => 6493),
            array('id' => 905, 'isim' => 'Gölyaka', 'state_id' =>6493),
            array('id' => 906, 'isim' => 'Çilimli', 'state_id' =>6493),
            array('id' => 907, 'isim' => 'Gümüsova', 'state_id' => 6493),
            array('id' => 908, 'isim' => 'Merkez', 'state_id' => 6493)


		);
        DB::table('cities')->insert($cities);
    }
}