<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
/**
* Run the database seeds.
*
* @return void
*/
public function run()
{
	DB::table('countries')->delete();
	$countries = array(
            array('id' => 1, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '+93', 'desi_id' => 4, 'ulke_kodu'  => 'AF', 'trisim' => 'Afganistan', 'engisim' => 'Afghanistan'),
            array('id' => 2, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' =>  4, 'ulke_kodu'  => '  AL', 'trisim' => 'Arnavutluk', 'engisim' => 'Albania'),
            array('id' => 3, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' =>  '', 'desi_id' =>  6, 'ulke_kodu'  => 'DZ', 'trisim' => 'Cezayir', 'engisim' => 'Algeria'),
            array('id' => 4, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '',  'desi_id' => 9, 'ulke_kodu'  =>   'AS', 'trisim' => 'Amerikan Samoasi', 'engisim' => 'American Samoa'),
            array('id' => 5, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '',  'desi_id' => 4, 'ulke_kodu'  =>   'AD', 'trisim' => 'Andorra', 'engisim' =>  'Andorra'),
            array('id' => 6, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' =>  '', 'desi_id' =>  9, 'ulke_kodu'  => 'AO', 'trisim' => 'Angora', 'engisim' => 'Angola'),
            array('id' => 7, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '',  'desi_id' => 9, 'ulke_kodu'  =>   'AL', 'trisim' => 'Anguilla', 'engisim' =>  'Anguilla'),
            array('id' => 8, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' =>  '', 'desi_id' =>  0, 'ulke_kodu'  =>  '', 'trisim' => 'Antarktika', 'engisim' => 'Antarctica'),
            array('id' => 9, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '',  'desi_id' => 8, 'ulke_kodu'  =>   'AG', 'trisim' => 'Antigua ve Barbuda', 'engisim' =>  'Antigua & Barbuda'),
            array('id' => 10, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' =>  '', 'desi_id' =>  8, 'ulke_kodu'  =>  'AR', 'trisim' => 'Arjantin', 'engisim' => 'Argentina'),
            array('id' => 11, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' =>  '', 'desi_id' =>  4, 'ulke_kodu'  =>  'AM', 'trisim' => 'Ermenistan', 'engisim' =>  'Armenia'),
            array('id' => 12, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' =>  '', 'desi_id' =>  8, 'ulke_kodu'  =>  'AW', 'trisim' => 'Aruba', 'engisim' =>  'Aruba'),
            array('id' => 13, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' =>  '', 'desi_id' =>  7, 'ulke_kodu'  =>  'AU', 'trisim' => 'Avustralya', 'engisim' => 'Australia'),
            array('id' => 14, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' =>  '', 'desi_id' =>  2, 'ulke_kodu'  =>  'AT', 'trisim' => 'Avusturya', 'engisim' =>  'Austria'),
            array('id' => 15, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' =>  '', 'desi_id' =>  4, 'ulke_kodu'  =>  'AZ', 'trisim' => 'Azerbaycan', 'engisim' => 'Azerbaijan'),
            array('id' => 16, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' =>  '', 'desi_id' =>  8, 'ulke_kodu'  =>  'BS', 'trisim' => 'Bahamalar', 'engisim' =>  'Bahamas'),
            array('id' => 17, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' =>  '', 'desi_id' =>  4, 'ulke_kodu'  =>  'BH', 'trisim' => 'Bahreyn', 'engisim' =>  'Bahrain'),
            array('id' => 18, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' =>  '', 'desi_id' =>  7, 'ulke_kodu'  =>  'BD', 'trisim' => 'Banglades', 'engisim' => 'Bangladesh'),
            array('id' => 19, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>      'BB', 'trisim' => 'Barbados', 'engisim' => 'Barbados'),
            array('id' => 20, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>       'BY', 'trisim' => 'Belarus', 'engisim' => 'Belarus'),
            array('id' => 21, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 2, 'ulke_kodu'  =>   'BE', 'trisim' => 'Belçika', 'engisim' => 'Belgium'),
            array('id' => 22, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'BZ', 'trisim' => 'Belize',  'engisim' => 'Belize'),
            array('id' => 23, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'BJ', 'trisim' => 'Benin',  'engisim' => 'Benin'),
            array('id' => 24, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'BM', 'trisim' => 'Bermuda', 'engisim' => 'Bermuda'),
            array('id' => 25, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'BT', 'trisim' => 'Bhutan',  'engisim' => 'Bhutan'),
            array('id' => 26, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'BQ', 'trisim' => 'Bolivya', 'engisim' => 'Bolivia'),
            array('id' => 27, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'BA', 'trisim' => 'Bosna-Hersek',  'engisim' => 'Bosnia-Herzegovina'),
            array('id' => 28, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' =>   '', 'desi_id' => 9, 'ulke_kodu'  =>    'BW', 'trisim' => 'Botsvana', 'engisim' => 'Botswana'),
            array('id' => 29, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'BR', 'trisim' => 'Brezilya', 'engisim' => 'Brazil'),
            array('id' => 30, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'VG', 'trisim' => 'Ingiliz Virgin Adalari', 'engisim' => 'British Virgin Islands'),
            array('id' => 31, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'BN', 'trisim' => 'Brunei', 'engisim' => 'Brunei'),
            array('id' => 32, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'BG', 'trisim' => 'Bulgaristan', 'engisim' => 'Bulgaria'),
            array('id' => 33, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'BF', 'trisim' => 'Burkina Faso', 'engisim' => 'Burkina Faso'),
            array('id' => 34, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'BI', 'trisim' => 'Burundi', 'engisim' => 'Burundi'),
            array('id' => 35, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'KH', 'trisim' => 'Kamboçya', 'engisim' => 'Cambodia'),
            array('id' => 36, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'CM', 'trisim' => 'Kamerun', 'engisim' => 'Cameroon'),
            array('id' => 37, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  =>  'CA', 'trisim' => 'Kanada',  'engisim' => 'Canada'),
            array('id' => 38, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'CV', 'trisim' => 'Cape Verde', 'engisim' => 'Cape Verde'),
            array('id' => 39, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  =>  'KY', 'trisim' => 'Cayman Adalari', 'engisim' => 'Cayman Islands'),
            array('id' => 40, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'CF', 'trisim' => 'Orta Afrika', 'engisim' => 'Central Africa'),
            array('id' => 41, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'TD', 'trisim' => 'Chad', 'engisim' => 'Chad'),
            array('id' => 42, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  =>  'CL', 'trisim' => 'Sili', 'engisim' => 'Chile'),
            array('id' => 43, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'CN', 'trisim' => 'Çin',  'engisim' => 'China'),
            array('id' => 44, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'CO', 'trisim' => 'Kolombiya', 'engisim' => 'Colombia'),
            array('id' => 45, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'KM', 'trisim' => 'Komorlar',  'engisim' => 'Comoros'),
            array('id' => 46, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'CG', 'trisim' => 'Kongo', 'engisim' => 'Congo'),
            array('id' => 47, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'CD', 'trisim' => 'Kongo (Dem. Cumhuriyeti)', 'engisim' => 'Congo (Dem. Rep.)'),
            array('id' => 48, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'CK', 'trisim' => 'Cook Adalari', 'engisim' => 'Cook Islands'),
            array('id' => 49, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'CR', 'trisim' => 'Kostarika', 'engisim' => 'Costa Rica'),
            array('id' => 50, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'HR', 'trisim' => 'Hirvatistan', 'engisim' => 'Croatia'),
            array('id' => 51, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'CU', 'trisim' => 'Küba', 'engisim' => 'Cuba'),
            array('id' => 52, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'CY', 'trisim' => 'Kibris', 'engisim' => 'Cyprus'),
            array('id' => 53, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'CZ', 'trisim' => 'Çek Cumhuriyeti', 'engisim' => 'Czech Republic'),
            array('id' => 54, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'DK', 'trisim' => 'Danimarka', 'engisim' => 'Denmark'),
            array('id' => 55, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'DJ', 'trisim' => 'Cibuti', 'engisim' => 'Djibouti'),
            array('id' => 56, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'DM', 'trisim' => 'Dominika', 'engisim' => 'Dominica'),
            array('id' => 57, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'DO', 'trisim' => 'Dominik Cumhuriyeti', 'engisim' => 'Dominican Republic'),
            array('id' => 58, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'TL', 'trisim' => 'Dogu Timor', 'engisim' => 'East Timor'),
            array('id' => 59, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'EC', 'trisim' => 'Ekvador', 'engisim' => 'Ecuador'),
            array('id' => 60, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>  'EG', 'trisim' => 'Misir', 'engisim' => 'Egypt'),
            array('id' => 61, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'SV', 'trisim' => 'El Salvador', 'engisim' => 'El Salvador'),
            array('id' => 62, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GQ', 'trisim' => 'Ekvator Ginesi', 'engisim' => 'Equatorial Guinea'),
            array('id' => 63, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'ER', 'trisim' => 'Eritre',  'engisim' => 'Eritrea'),
            array('id' => 64, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'EE', 'trisim' => 'Estonya', 'engisim' => 'Estonia'),
            array('id' => 65, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'ET', 'trisim' => 'Etiyopya', 'engisim' => 'Ethiopia'),
            array('id' => 66, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'ACT', 'trisim' => 'Ext. Territ. Avustralya', 'engisim' => 'Ext. Territ. of Australia'),
            array('id' => 67, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'FK', 'trisim' => 'Falkland Adalari', 'engisim' => 'Falkland Islands'),
            array('id' => 68, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'FO', 'trisim' => 'Faroe Adalari', 'engisim' => 'Faroe Islands'),
            array('id' => 69, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'FJ', 'trisim' => 'Fiji', 'engisim' => 'Fiji'),
            array('id' => 70, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'FI', 'trisim' => 'Finlandiya', 'engisim' => 'Finland'),
            array('id' => 71, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'FR', 'trisim' => 'Fransa', 'engisim' => 'France'),
            array('id' => 72, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'GF', 'trisim' => 'Fransiz Guyanasi', 'engisim' => 'French Guiana'),
            array('id' => 73, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'PF', 'trisim' => 'Fransiz Polinezyasi', 'engisim' => 'French Polynesia'),
            array('id' => 74, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GA', 'trisim' => 'Gabon', 'engisim' => 'Gabon'),
            array('id' => 75, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GM', 'trisim' => 'Gambiya', 'engisim' => 'Gambia'),
            array('id' => 76, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'GE', 'trisim' => 'Gürcistan', 'engisim' => 'Georgia'),
            array('id' => 77, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 1,  'ulke_kodu'  => 'DE', 'trisim' => 'Almanya', 'engisim' => 'Germany'),
            array('id' => 78, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GH', 'trisim' => 'Gana', 'engisim' => 'Ghana'),
            array('id' => 79, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'GL', 'trisim' => 'Cebelitarik', 'engisim' => 'Gibraltar'),
            array('id' => 80, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'GR', 'trisim' => 'Yunanistan', 'engisim' => 'Greece'),
            array('id' => 81, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'GL', 'trisim' => 'Grönland', 'engisim' => 'Greenland'),
            array('id' => 82, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'GD', 'trisim' => 'Grenada', 'engisim' => 'Grenada'),
            array('id' => 83, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'GP', 'trisim' => 'Guadeloupe', 'engisim' => 'Guadeloupe'),
            array('id' => 84, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'GU', 'trisim' => 'Guam', 'engisim' => 'Guam'),
            array('id' => 85, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'GT', 'trisim' => 'Guatemala', 'engisim' => 'Guatemala'),
            array('id' => 86, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'GG', 'trisim' => 'Guernsey ve Alderney', 'engisim' => 'Guernsey and Alderney'),
            array('id' => 87, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GN', 'trisim' => 'Gine', 'engisim' => 'Guinea'),
            array('id' => 88, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GW', 'trisim' => 'Gine Bissau', 'engisim' => 'Guinea Bissau'),
            array('id' => 89, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'GY', 'trisim' => 'Guyana', 'engisim' => 'Guyana'),
            array('id' => 90, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'HT', 'trisim' => 'Haiti', 'engisim' => 'Haiti'),
            array('id' => 91, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'HN', 'trisim' => 'Honduras', 'engisim' => 'Honduras'),
            array('id' => 92, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'HU', 'trisim' => 'Macaristan', 'engisim' => 'Hungary'),
            array('id' => 93, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'IS', 'trisim' => 'Izlanda', 'engisim' => 'Iceland'),
            array('id' => 94, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'IN', 'trisim' => 'Hindistan', 'engisim' => 'India'),
            array('id' => 95, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'ID', 'trisim' => 'Endonezya', 'engisim' => 'Indonesia'),
            array('id' => 96, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'IR', 'trisim' => 'Iran',  'engisim' => 'Iran'),
            array('id' => 97, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'IQ', 'trisim' => 'Irak',  'engisim' => 'Iraq'),
            array('id' => 98, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'IE', 'trisim' => 'Irlanda', 'engisim' => 'Ireland'),
            array('id' => 99, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'IL', 'trisim' => 'Israil',  'engisim' => 'Israel'),
            array('id' => 100, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 2, 'ulke_kodu'  =>  'IT', 'trisim' => 'Italya',  'engisim' => 'Italy'),
            array('id' => 101, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'CI', 'trisim' => 'Fildisi Sahili', 'engisim' => 'Ivory Coast'),
            array('id' => 102, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'JM', 'trisim' => 'Jamaika',  'engisim' => 'Jamaica'),
            array('id' => 103, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6, 'ulke_kodu'  =>  'JP', 'trisim' => 'Japonya',  'engisim' => 'Japan'),
            array('id' => 104, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>  'JE', 'trisim' => 'Jarse',  'engisim' => 'Jersey'),
            array('id' => 105, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>  'JO', 'trisim' => 'Ürdün',  'engisim' => 'Jordan'),
            array('id' => 106, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>  'KZ', 'trisim' => 'Kazakistan', 'engisim' => 'Kazakhstan'),
            array('id' => 107, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 7, 'ulke_kodu'  =>  'KE', 'trisim' => 'Kenya', 'engisim' => 'Kenya'),
            array('id' => 108, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'KL', 'trisim' => 'Kiribati', 'engisim' => 'Kiribati'),
            array('id' => 109, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'KP', 'trisim' => 'Kore (Kuzey)', 'engisim' => 'Korea (North)'),
            array('id' => 110, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'KR', 'trisim' => 'Kore (Güney)', 'engisim' => 'Korea (South)'),
            array('id' => 111, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'KW', 'trisim' => 'Kuveyt', 'engisim' => 'Kuwait'),
            array('id' => 112, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'KG', 'trisim' => 'Kirgizistan', 'engisim' => 'Kyrgyzstan'),
            array('id' => 113, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'LA', 'trisim' => 'Laos', 'engisim' => 'Laos'),
            array('id' => 114, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'LV', 'trisim' => 'Letonya', 'engisim' => 'Latvia'),
            array('id' => 115, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'LB', 'trisim' => 'Lübnan',  'engisim' => 'Lebanon'),
            array('id' => 116, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 7, 'ulke_kodu'  =>  'LS', 'trisim' => 'Lesotho', 'engisim' => 'Lesotho'),
            array('id' => 117, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'LR', 'trisim' => 'Liberya', 'engisim' => 'Liberia'),
            array('id' => 118, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 6, 'ulke_kodu'  =>  'LY', 'trisim' => 'Libya', 'engisim' => 'Libya'),
            array('id' => 119, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'LI', 'trisim' => 'Liechtenstein', 'engisim' => 'Liechtenstein'),
            array('id' => 120, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'LT', 'trisim' => 'Litvanya', 'engisim' => 'Lithuania'),
            array('id' => 121, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'LU', 'trisim' => 'Lüksemburg', 'engisim' => 'Luxembourg'),
            array('id' => 122, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'MK', 'trisim' => 'Makedonya',  'engisim' => 'Macedonia'),
            array('id' => 123, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'MG', 'trisim' => 'Madagaskar', 'engisim' => 'Madagascar'),
            array('id' => 124, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'MW', 'trisim' => 'Malawi', 'engisim' => 'Malawi'),
            array('id' => 125, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'MY', 'trisim' => 'Malezya', 'engisim' => 'Malaysia'),
            array('id' => 126, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'MV', 'trisim' => 'Maldivler', 'engisim' => 'Maldives'),
            array('id' => 127, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'ML', 'trisim' => 'Mali',  'engisim' => 'Mali'),
            array('id' => 128, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'MT', 'trisim' => 'Malta', 'engisim' => 'Malta'),
            array('id' => 129, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'IM', 'trisim' => 'Man Adasi', 'engisim' => 'Man (Isle of)'),
            array('id' => 130, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'MH', 'trisim' => 'Marshall Adalari', 'engisim' => 'Marshall Islands'),
            array('id' => 131, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'MQ', 'trisim' => 'Martinik',  'engisim' => 'Martinique'),
            array('id' => 132, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'MR', 'trisim' => 'Moritanya', 'engisim' => 'Mauritania'),
            array('id' => 133, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'MU', 'trisim' => 'Mauritius', 'engisim' => 'Mauritius'),
            array('id' => 134, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'YT', 'trisim' => 'Mayotte',  'engisim' => 'Mayotte'),
            array('id' => 135, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  => 'MX', 'trisim' => 'Meksika',  'engisim' => 'Mexico'),
            array('id' => 136, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'FM', 'trisim' => 'Mikronezya', 'engisim' => 'Micronesia'),
            array('id' => 137, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'MD', 'trisim' => 'Moldova', 'engisim' => 'Moldova'),
            array('id' => 138, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'MC', 'trisim' => 'Monako', 'engisim' => 'Monaco'),
            array('id' => 139, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'MN', 'trisim' => 'Mogolistan', 'engisim' => 'Mongolia'),
            array('id' => 140, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 7, 'ulke_kodu'  =>  'MA', 'trisim' => 'Fas', 'engisim' => 'Morocco'),
            array('id' => 141, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'MZ', 'trisim' => 'Mozambik', 'engisim' => 'Mozambique'),
            array('id' => 142, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'MM', 'trisim' => 'Myanmar',  'engisim' => 'Myanmar'),
            array('id' => 143, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'NA', 'trisim' => 'Namibya',  'engisim' => 'Namibia'),
            array('id' => 144, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  => 'NR', 'trisim' => 'Nauru',  'engisim' => 'Nauru'),
            array('id' => 145, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'NP', 'trisim' => 'Nepal',  'engisim' => 'Nepal'),
            array('id' => 146, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'NL', 'trisim' => 'Hollanda', 'engisim' => 'Netherlands'),
            array('id' => 147, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'AN', 'trisim' => 'Hollanda Antilleri', 'engisim' => 'Netherlands Antilles'),
            array('id' => 148, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'NC', 'trisim' => 'Yeni Kaledonya', 'engisim' => 'New Caledonia'),
            array('id' => 149, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'NZ', 'trisim' => 'Yeni Zelanda', 'engisim' => 'New Zealand'),
            array('id' => 150, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'NI', 'trisim' => 'Nikaragua', 'engisim' => 'Nicaragua'),
            array('id' => 151, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'NE', 'trisim' => 'Nijer', 'engisim' => 'Niger'),
            array('id' => 152, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 7, 'ulke_kodu'  =>  'NG', 'trisim' => 'Nijerya', 'engisim' => 'Nigeria'),
            array('id' => 153, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  => 'NU', 'trisim' => 'Niue',  'engisim' => 'Niue'),
            array('id' => 154, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => '', 'trisim' => 'Norfolk', 'engisim' => 'Norfolk'),
            array('id' => 155, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'MP', 'trisim' => 'Kuzey Mariana Adalari', 'engisim' => 'Northern Mariana Islands'),
            array('id' => 156, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'OM', 'trisim' => 'Umman', 'engisim' => 'Oman'),
            array('id' => 157, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'PK', 'trisim' => 'Pakistan', 'engisim' => 'Pakistan'),
            array('id' => 158, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'PW', 'trisim' => 'Palau', 'engisim' => 'Palau'),
            array('id' => 159, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'PS', 'trisim' => 'Filistin', 'engisim' => 'Palestine'),
            array('id' => 160, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'PA', 'trisim' => 'Panama', 'engisim' => 'Panama'),
            array('id' => 161, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'PG', 'trisim' => 'Papua Yeni Gine', 'engisim' => 'Papua New Guinea'),
            array('id' => 162, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'PY', 'trisim' => 'Paraguay', 'engisim' => 'Paraguay'),
            array('id' => 163, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'PE', 'trisim' => 'Peru', 'engisim' => 'Peru'),
            array('id' => 164, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'PH', 'trisim' => 'Filipinler', 'engisim' => 'Philippines'),
            array('id' => 165, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'PL', 'trisim' => 'Polonya',  'engisim' => 'Poland'),
            array('id' => 166, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'PT', 'trisim' => 'Portekiz', 'engisim' => 'Portugal'),
            array('id' => 167, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  => 'PR', 'trisim' => 'Porto Riko', 'engisim' => 'Puerto Rico'),
            array('id' => 168, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'QA', 'trisim' => 'Qatar', 'engisim' => 'Qatar'),
            array('id' => 169, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'RE', 'trisim' => 'Réunion',  'engisim' => 'Réunion'),
            array('id' => 170, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'RO', 'trisim' => 'Romanya',  'engisim' => 'Romania'),
            array('id' => 171, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'RU', 'trisim' => 'Rusya',  'engisim' => 'Russia'),
            array('id' => 172, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'RW', 'trisim' => 'Ruanda', 'engisim' => 'Rwanda'),
            array('id' => 173, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 0, 'ulke_kodu'  =>  '', 'trisim' => 'Sahara', 'engisim' => 'Sahara'),
            array('id' => 174, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'SH', 'trisim' => 'Saint Helena', 'engisim' => 'Saint Helena'),
            array('id' => 175, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'KN', 'trisim' => 'Saint Kitts ve Nevis', 'engisim' => 'Saint Kitts and Nevis'),
            array('id' => 176, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'LC', 'trisim' => 'Saint Lucia', 'engisim' => 'Saint Lucia'),
            array('id' => 177, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'PM', 'trisim' => 'Saint Pierre ve Miquelon', 'engisim' => 'Saint Pierre & Miquelon'),
            array('id' => 178, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'VC', 'trisim' => 'St Vincent ve Grenadinler', 'engisim' => 'St. Vincent & the Grenadines'),
            array('id' => 179, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'WS', 'trisim' => 'Samoa', 'engisim' => 'Samoa'),
            array('id' => 180, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'SM', 'trisim' => 'San Marino', 'engisim' => 'San Marino'),
            array('id' => 181, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 0, 'ulke_kodu'  =>  'ST', 'trisim' => 'Sao Tome ve Principe', 'engisim' => 'São Tomé and Príncipe'),
            array('id' => 182, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'SA', 'trisim' => 'Suudi Arabistan', 'engisim' => 'Saudi Arabia'),
            array('id' => 183, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'SN', 'trisim' => 'Senegal', 'engisim' => 'Senegal'),
            array('id' => 184, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'RS', 'trisim' => 'Sirbistan', 'engisim' => 'Serbia and Montenegro'),
            array('id' => 185, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'SC', 'trisim' => 'Seysel Adalari', 'engisim' => 'Seychelles'),
            array('id' => 186, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 6, 'ulke_kodu'  =>  'SL', 'trisim' => 'Sierra Leone', 'engisim' => 'Sierra Leone'),
            array('id' => 187, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'SG', 'trisim' => 'Singapur',  'engisim' => 'Singapore'),
            array('id' => 188, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'SK', 'trisim' => 'Slovakya',  'engisim' => 'Slovakia'),
            array('id' => 189, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'SI', 'trisim' => 'Slovenya',  'engisim' => 'Slovenia'),
            array('id' => 190, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => '', 'trisim' => 'Smaller Territories of the UK', 'engisim' => 'Smaller Territories of the UK'),
            array('id' => 191, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'SB', 'trisim' => 'Solomon Adalari', 'engisim' => 'Solomon Islands'),
            array('id' => 192, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>  'SO', 'trisim' => 'Somali', 'engisim' => 'Somalia'),
            array('id' => 193, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 7, 'ulke_kodu'  =>  'ZA', 'trisim' => 'Güney Afrika', 'engisim' => 'South Africa'),
            array('id' => 194, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'ES', 'trisim' => 'Ispanya', 'engisim' => 'Spain'),
            array('id' => 195, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'LK', 'trisim' => 'Sri Lanka', 'engisim' => 'Sri Lanka'),
            array('id' => 196, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 3, 'ulke_kodu'  =>  'SD', 'trisim' => 'Sudan', 'engisim' => 'Sudan'),
            array('id' => 197, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'SR', 'trisim' => 'Surinam', 'engisim' => 'Suriname'),
            array('id' => 198, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'NO', 'trisim' => 'Svalbard ve Jan Mayen', 'engisim' => 'Svalbard and Jan Mayen'),
            array('id' => 199, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 2, 'ulke_kodu'  =>  'SZ', 'trisim' => 'Svaziland', 'engisim' => 'Swaziland'),
            array('id' => 200, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'SE', 'trisim' => 'Isveç', 'engisim' => 'Sweden'),
            array('id' => 201, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'CH', 'trisim' => 'Isviçre', 'engisim' => 'Switzerland'),
            array('id' => 202, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'SY', 'trisim' => 'Suriye',  'engisim' => 'Syria'),
            array('id' => 203, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'WT', 'trisim' => 'Tayvan',  'engisim' => 'Taiwan'),
            array('id' => 204, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'TJ', 'trisim' => 'Tacikistan', 'engisim' => 'Tajikistan'),
            array('id' => 205, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'TZ', 'trisim' => 'Tanzanya', 'engisim' => 'Tanzania'),
            array('id' => 206, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 0, 'ulke_kodu'  =>  '', 'trisim' => 'Terres Australes', 'engisim' => 'Terres Australes'),
            array('id' => 207, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'TH', 'trisim' => 'Tayland', 'engisim' => 'Thailand'),
            array('id' => 208, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'TG', 'trisim' => 'Togo', 'engisim' => 'Togo'),
            array('id' => 209, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'TK', 'trisim' => 'Tokelau', 'engisim' => 'Tokelau'),
            array('id' => 210, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'TO', 'trisim' => 'Tonga', 'engisim' => 'Tonga'),
            array('id' => 211, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'TT', 'trisim' => 'Trinidad ve Tobago', 'engisim' => 'Trinidad and Tobago'),
            array('id' => 212, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 6, 'ulke_kodu'  =>  'TN', 'trisim' => 'Tunus', 'engisim' => 'Tunisia'),
            array('id' => 213, 'region_id' => 2, 'country_code' => 'TR',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'TR', 'trisim' => 'Türkiye', 'engisim' => 'Türkiye'),
            array('id' => 214, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'TM', 'trisim' => 'Türkmenistan', 'engisim' => 'Turkmenistan'),
            array('id' => 215, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'TC', 'trisim' => 'Turks ve Caicos Adalari', 'engisim' => 'Turks and Caicos Islands'),
            array('id' => 216, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'TV', 'trisim' => 'Tuvalu', 'engisim' => 'Tuvalu'),
            array('id' => 217, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'UG', 'trisim' => 'Uganda',  'engisim' => 'Uganda'),
            array('id' => 218, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'UA', 'trisim' => 'Ukrayna', 'engisim' => 'Ukraine'),
            array('id' => 219, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'AE', 'trisim' => 'Birlesik Arap Emirlikleri', 'engisim' => 'United Arab Emirates'),
            array('id' => 220, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'GB', 'trisim' => 'Ingiltere', 'engisim' =>  'United Kingdom'),
            array('id' => 221, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  => 'US', 'trisim' => 'Amerika Birlesik Devletleri', 'engisim' => 'United States of America'),
            array('id' => 222, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'UY', 'trisim' => 'Uruguay', 'engisim' => 'Uruguay'),
            array('id' => 223, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'UZ', 'trisim' => 'Özbekistan', 'engisim' => 'Uzbekistan'),
            array('id' => 224, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'VU', 'trisim' => 'Vanuatu', 'engisim' => 'Vanuatu'),
            array('id' => 225, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'VA', 'trisim' => 'Vatikan', 'engisim' => 'Vatican'),
            array('id' => 226, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'VE', 'trisim' => 'Venezuela', 'engisim' => 'Venezuela'),
            array('id' => 227, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'VN', 'trisim' => 'Vietnam', 'engisim' => 'Vietnam'),
            array('id' => 228, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'VI', 'trisim' => 'Virgin Adalari', 'engisim' => 'Virgin Islands of the USA'),
            array('id' => 229, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'WF', 'trisim' => 'Wallis ve Futuna', 'engisim' => 'Wallis & Futuna'),
            array('id' => 230, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'YE', 'trisim' => 'Yemen', 'engisim' => 'Yemen'),
            array('id' => 231, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'ZM', 'trisim' => 'Zambiya', 'engisim' => 'Zambia'),
            array('id' => 232, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'ZW', 'trisim' => 'Zimbabve', 'engisim' => 'Zimbabwe'),
            array('id' => 233, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'GB', 'trisim' => 'Büyük Britanya', 'engisim' => 'Great Britain'),
            array('id' => 234, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'ME', 'trisim' => 'Karadag', 'engisim' => 'Karadag'),
            array('id' => 235, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'NO', 'trisim' => 'Norvec', 'engisim' => 'Norvec'),
            array('id' => 236, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'KV', 'trisim' => 'Kosova', 'engisim' => 'Kosovo'),
            array('id' => 237, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'IC', 'trisim' => 'Kanarya Adalar', 'engisim' => 'Kanarya Adalar'),

    );
		DB::table('countries')->insert($countries);
	}
}