<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(


            array('id' => 1, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '+93', 'desi_id' => 4, 'ulke_kodu'  => 'AF', 'trisim' => 'Afganistan', 'engisim' => 'Afghanistan'),
            array('id' => 2, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' =>  4, 'ulke_kodu'  => '  AL', 'trisim' => 'Arnavutluk', 'engisim' => 'Albania'),
            array('id' => 3, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' =>  '', 'desi_id' =>  6, 'ulke_kodu'  => 'DZ', 'trisim' => 'Cezayir', 'engisim' => 'Algeria'),
            array('id' => 4, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '',  'desi_id' => 9, 'ulke_kodu'  =>   'AS', 'trisim' => 'Amerikan Samoasi', 'engisim' => 'American Samoa'),
            array('id' => 5, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '',  'desi_id' => 4, 'ulke_kodu'  =>   'AD', 'trisim' => 'Andorra', 'engisim' =>  'Andorra'),
            array('id' => 6, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' =>  '', 'desi_id' =>  9, 'ulke_kodu'  => 'AO', 'trisim' => 'Angora', 'engisim' => 'Angola'),
            array('id' => 7, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '',  'desi_id' => 9, 'ulke_kodu'  =>   'AL', 'trisim' => 'Anguilla', 'engisim' =>  'Anguilla'),
            array('id' => 8, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' =>  '', 'desi_id' =>  0, 'ulke_kodu'  =>  '', 'trisim' => 'Antarktika', 'engisim' => 'Antarctica'),
            array('id' => 9, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '',  'desi_id' => 8, 'ulke_kodu'  =>   'AG', 'trisim' => 'Antigua ve Barbuda', 'engisim' =>  'Antigua & Barbuda'),
            array('id' => 10, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' =>  '', 'desi_id' =>  8, 'ulke_kodu'  =>  'AR', 'trisim' => 'Arjantin', 'engisim' => 'Argentina'),
            array('id' => 11, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' =>  '', 'desi_id' =>  4, 'ulke_kodu'  =>  'AM', 'trisim' => 'Ermenistan', 'engisim' =>  'Armenia'),
            array('id' => 12, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' =>  '', 'desi_id' =>  8, 'ulke_kodu'  =>  'AW', 'trisim' => 'Aruba', 'engisim' =>  'Aruba'),
            array('id' => 13, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' =>  '', 'desi_id' =>  7, 'ulke_kodu'  =>  'AU', 'trisim' => 'Avustralya', 'engisim' => 'Australia'),
            array('id' => 14, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' =>  '', 'desi_id' =>  2, 'ulke_kodu'  =>  'AT', 'trisim' => 'Avusturya', 'engisim' =>  'Austria'),
            array('id' => 15, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' =>  '', 'desi_id' =>  4, 'ulke_kodu'  =>  'AZ', 'trisim' => 'Azerbaycan', 'engisim' => 'Azerbaijan'),
            array('id' => 16, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' =>  '', 'desi_id' =>  8, 'ulke_kodu'  =>  'BS', 'trisim' => 'Bahamalar', 'engisim' =>  'Bahamas'),
            array('id' => 17, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' =>  '', 'desi_id' =>  4, 'ulke_kodu'  =>  'BH', 'trisim' => 'Bahreyn', 'engisim' =>  'Bahrain'),
            array('id' => 18, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' =>  '', 'desi_id' =>  7, 'ulke_kodu'  =>  'BD', 'trisim' => 'Banglades', 'engisim' => 'Bangladesh'),
            array('id' => 19, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>      'BB', 'trisim' => 'Barbados', 'engisim' => 'Barbados'),
            array('id' => 20, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>       'BY', 'trisim' => 'Belarus', 'engisim' => 'Belarus'),
            array('id' => 21, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 2, 'ulke_kodu'  =>   'BE', 'trisim' => 'Belçika', 'engisim' => 'Belgium'),
            array('id' => 22, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'BZ', 'trisim' => 'Belize',  'engisim' => 'Belize'),
            array('id' => 23, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'BJ', 'trisim' => 'Benin',  'engisim' => 'Benin'),
            array('id' => 24, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'BM', 'trisim' => 'Bermuda', 'engisim' => 'Bermuda'),
            array('id' => 25, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'BT', 'trisim' => 'Bhutan',  'engisim' => 'Bhutan'),
            array('id' => 26, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'BQ', 'trisim' => 'Bolivya', 'engisim' => 'Bolivia'),
            array('id' => 27, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'BA', 'trisim' => 'Bosna-Hersek',  'engisim' => 'Bosnia-Herzegovina'),
            array('id' => 28, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' =>   '', 'desi_id' => 9, 'ulke_kodu'  =>    'BW', 'trisim' => 'Botsvana', 'engisim' => 'Botswana'),
            array('id' => 29, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'BR', 'trisim' => 'Brezilya', 'engisim' => 'Brazil'),
            array('id' => 30, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'VG', 'trisim' => 'Ingiliz Virgin Adalari', 'engisim' => 'British Virgin Islands'),
            array('id' => 31, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'BN', 'trisim' => 'Brunei', 'engisim' => 'Brunei'),
            array('id' => 32, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'BG', 'trisim' => 'Bulgaristan', 'engisim' => 'Bulgaria'),
            array('id' => 33, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'BF', 'trisim' => 'Burkina Faso', 'engisim' => 'Burkina Faso'),
            array('id' => 34, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'BI', 'trisim' => 'Burundi', 'engisim' => 'Burundi'),
            array('id' => 35, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'KH', 'trisim' => 'Kamboçya', 'engisim' => 'Cambodia'),
            array('id' => 36, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'CM', 'trisim' => 'Kamerun', 'engisim' => 'Cameroon'),
            array('id' => 37, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  =>  'CA', 'trisim' => 'Kanada',  'engisim' => 'Canada'),
            array('id' => 38, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'CV', 'trisim' => 'Cape Verde', 'engisim' => 'Cape Verde'),
            array('id' => 39, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  =>  'KY', 'trisim' => 'Cayman Adalari', 'engisim' => 'Cayman Islands'),
            array('id' => 40, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'CF', 'trisim' => 'Orta Afrika', 'engisim' => 'Central Africa'),
            array('id' => 41, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'TD', 'trisim' => 'Chad', 'engisim' => 'Chad'),
            array('id' => 42, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  =>  'CL', 'trisim' => 'Sili', 'engisim' => 'Chile'),
            array('id' => 43, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'CN', 'trisim' => 'Çin',  'engisim' => 'China'),
            array('id' => 44, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'CO', 'trisim' => 'Kolombiya', 'engisim' => 'Colombia'),
            array('id' => 45, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'KM', 'trisim' => 'Komorlar',  'engisim' => 'Comoros'),
            array('id' => 46, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'CG', 'trisim' => 'Kongo', 'engisim' => 'Congo'),
            array('id' => 47, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'CD', 'trisim' => 'Kongo (Dem. Cumhuriyeti)', 'engisim' => 'Congo (Dem. Rep.)'),
            array('id' => 48, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'CK', 'trisim' => 'Cook Adalari', 'engisim' => 'Cook Islands'),
            array('id' => 49, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'CR', 'trisim' => 'Kostarika', 'engisim' => 'Costa Rica'),
            array('id' => 50, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'HR', 'trisim' => 'Hirvatistan', 'engisim' => 'Croatia'),
            array('id' => 51, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'CU', 'trisim' => 'Küba', 'engisim' => 'Cuba'),
            array('id' => 52, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'CY', 'trisim' => 'Kibris', 'engisim' => 'Cyprus'),
            array('id' => 53, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'CZ', 'trisim' => 'Çek Cumhuriyeti', 'engisim' => 'Czech Republic'),
            array('id' => 54, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'DK', 'trisim' => 'Danimarka', 'engisim' => 'Denmark'),
            array('id' => 55, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'DJ', 'trisim' => 'Cibuti', 'engisim' => 'Djibouti'),
            array('id' => 56, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'DM', 'trisim' => 'Dominika', 'engisim' => 'Dominica'),
            array('id' => 57, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'DO', 'trisim' => 'Dominik Cumhuriyeti', 'engisim' => 'Dominican Republic'),
            array('id' => 58, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'TL', 'trisim' => 'Dogu Timor', 'engisim' => 'East Timor'),
            array('id' => 59, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'EC', 'trisim' => 'Ekvador', 'engisim' => 'Ecuador'),
            array('id' => 60, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>  'EG', 'trisim' => 'Misir', 'engisim' => 'Egypt'),
            array('id' => 61, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'SV', 'trisim' => 'El Salvador', 'engisim' => 'El Salvador'),
            array('id' => 62, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GQ', 'trisim' => 'Ekvator Ginesi', 'engisim' => 'Equatorial Guinea'),
            array('id' => 63, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'ER', 'trisim' => 'Eritre',  'engisim' => 'Eritrea'),
            array('id' => 64, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'EE', 'trisim' => 'Estonya', 'engisim' => 'Estonia'),
            array('id' => 65, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'ET', 'trisim' => 'Etiyopya', 'engisim' => 'Ethiopia'),
            array('id' => 66, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'ACT', 'trisim' => 'Ext. Territ. Avustralya', 'engisim' => 'Ext. Territ. of Australia'),
            array('id' => 67, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'FK', 'trisim' => 'Falkland Adalari', 'engisim' => 'Falkland Islands'),
            array('id' => 68, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'FO', 'trisim' => 'Faroe Adalari', 'engisim' => 'Faroe Islands'),
            array('id' => 69, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'FJ', 'trisim' => 'Fiji', 'engisim' => 'Fiji'),
            array('id' => 70, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'FI', 'trisim' => 'Finlandiya', 'engisim' => 'Finland'),
            array('id' => 71, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'FR', 'trisim' => 'Fransa', 'engisim' => 'France'),
            array('id' => 72, 'region_id' => 3, 'country_code' => 'US', 'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'GF', 'trisim' => 'Fransiz Guyanasi', 'engisim' => 'French Guiana'),
            array('id' => 73, 'region_id' => 4, 'country_code' => 'AS', 'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'PF', 'trisim' => 'Fransiz Polinezyasi', 'engisim' => 'French Polynesia'),
            array('id' => 74, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GA', 'trisim' => 'Gabon', 'engisim' => 'Gabon'),
            array('id' => 75, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GM', 'trisim' => 'Gambiya', 'engisim' => 'Gambia'),
            array('id' => 76, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'GE', 'trisim' => 'Gürcistan', 'engisim' => 'Georgia'),
            array('id' => 77, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 1,  'ulke_kodu'  => 'DE', 'trisim' => 'Almanya', 'engisim' => 'Germany'),
            array('id' => 78, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GH', 'trisim' => 'Gana', 'engisim' => 'Ghana'),
            array('id' => 79, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'GL', 'trisim' => 'Cebelitarik', 'engisim' => 'Gibraltar'),
            array('id' => 80, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'GR', 'trisim' => 'Yunanistan', 'engisim' => 'Greece'),
            array('id' => 81, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'GL', 'trisim' => 'Grönland', 'engisim' => 'Greenland'),
            array('id' => 82, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'GD', 'trisim' => 'Grenada', 'engisim' => 'Grenada'),
            array('id' => 83, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'GP', 'trisim' => 'Guadeloupe', 'engisim' => 'Guadeloupe'),
            array('id' => 84, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'GU', 'trisim' => 'Guam', 'engisim' => 'Guam'),
            array('id' => 85, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'GT', 'trisim' => 'Guatemala', 'engisim' => 'Guatemala'),
            array('id' => 86, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'GG', 'trisim' => 'Guernsey ve Alderney', 'engisim' => 'Guernsey and Alderney'),
            array('id' => 87, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GN', 'trisim' => 'Gine', 'engisim' => 'Guinea'),
            array('id' => 88, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'GW', 'trisim' => 'Gine Bissau', 'engisim' => 'Guinea Bissau'),
            array('id' => 89, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'GY', 'trisim' => 'Guyana', 'engisim' => 'Guyana'),
            array('id' => 90, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'HT', 'trisim' => 'Haiti', 'engisim' => 'Haiti'),
            array('id' => 91, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'HN', 'trisim' => 'Honduras', 'engisim' => 'Honduras'),
            array('id' => 92, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'HU', 'trisim' => 'Macaristan', 'engisim' => 'Hungary'),
            array('id' => 93, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'IS', 'trisim' => 'Izlanda', 'engisim' => 'Iceland'),
            array('id' => 94, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'IN', 'trisim' => 'Hindistan', 'engisim' => 'India'),
            array('id' => 95, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'ID', 'trisim' => 'Endonezya', 'engisim' => 'Indonesia'),
            array('id' => 96, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'IR', 'trisim' => 'Iran',  'engisim' => 'Iran'),
            array('id' => 97, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'IQ', 'trisim' => 'Irak',  'engisim' => 'Iraq'),
            array('id' => 98, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'IE', 'trisim' => 'Irlanda', 'engisim' => 'Ireland'),
            array('id' => 99, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'IL', 'trisim' => 'Israil',  'engisim' => 'Israel'),
            array('id' => 100, 'region_id' => 1, 'country_code' => 'EU', 'country_phone_code' => '', 'desi_id' => 2, 'ulke_kodu'  =>  'IT', 'trisim' => 'Italya',  'engisim' => 'Italy'),
            array('id' => 101, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'CI', 'trisim' => 'Fildisi Sahili', 'engisim' => 'Ivory Coast'),
            array('id' => 102, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'JM', 'trisim' => 'Jamaika',  'engisim' => 'Jamaica'),
            array('id' => 103, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6, 'ulke_kodu'  =>  'JP', 'trisim' => 'Japonya',  'engisim' => 'Japan'),
            array('id' => 104, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>  'JE', 'trisim' => 'Jarse',  'engisim' => 'Jersey'),
            array('id' => 105, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>  'JO', 'trisim' => 'Ürdün',  'engisim' => 'Jordan'),
            array('id' => 106, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>  'KZ', 'trisim' => 'Kazakistan', 'engisim' => 'Kazakhstan'),
            array('id' => 107, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 7, 'ulke_kodu'  =>  'KE', 'trisim' => 'Kenya', 'engisim' => 'Kenya'),
            array('id' => 108, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'KL', 'trisim' => 'Kiribati', 'engisim' => 'Kiribati'),
            array('id' => 109, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'KP', 'trisim' => 'Kore (Kuzey)', 'engisim' => 'Korea (North)'),
            array('id' => 110, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'KR', 'trisim' => 'Kore (Güney)', 'engisim' => 'Korea (South)'),
            array('id' => 111, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'KW', 'trisim' => 'Kuveyt', 'engisim' => 'Kuwait'),
            array('id' => 112, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'KG', 'trisim' => 'Kirgizistan', 'engisim' => 'Kyrgyzstan'),
            array('id' => 113, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'LA', 'trisim' => 'Laos', 'engisim' => 'Laos'),
            array('id' => 114, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'LV', 'trisim' => 'Letonya', 'engisim' => 'Latvia'),
            array('id' => 115, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'LB', 'trisim' => 'Lübnan',  'engisim' => 'Lebanon'),
            array('id' => 116, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 7, 'ulke_kodu'  =>  'LS', 'trisim' => 'Lesotho', 'engisim' => 'Lesotho'),
            array('id' => 117, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'LR', 'trisim' => 'Liberya', 'engisim' => 'Liberia'),
            array('id' => 118, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 6, 'ulke_kodu'  =>  'LY', 'trisim' => 'Libya', 'engisim' => 'Libya'),
            array('id' => 119, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'LI', 'trisim' => 'Liechtenstein', 'engisim' => 'Liechtenstein'),
            array('id' => 120, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'LT', 'trisim' => 'Litvanya', 'engisim' => 'Lithuania'),
            array('id' => 121, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'LU', 'trisim' => 'Lüksemburg', 'engisim' => 'Luxembourg'),
            array('id' => 122, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'MK', 'trisim' => 'Makedonya',  'engisim' => 'Macedonia'),
            array('id' => 123, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'MG', 'trisim' => 'Madagaskar', 'engisim' => 'Madagascar'),
            array('id' => 124, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'MW', 'trisim' => 'Malawi', 'engisim' => 'Malawi'),
            array('id' => 125, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'MY', 'trisim' => 'Malezya', 'engisim' => 'Malaysia'),
            array('id' => 126, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'MV', 'trisim' => 'Maldivler', 'engisim' => 'Maldives'),
            array('id' => 127, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'ML', 'trisim' => 'Mali',  'engisim' => 'Mali'),
            array('id' => 128, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'MT', 'trisim' => 'Malta', 'engisim' => 'Malta'),
            array('id' => 129, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'IM', 'trisim' => 'Man Adasi', 'engisim' => 'Man (Isle of)'),
            array('id' => 130, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'MH', 'trisim' => 'Marshall Adalari', 'engisim' => 'Marshall Islands'),
            array('id' => 131, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'MQ', 'trisim' => 'Martinik',  'engisim' => 'Martinique'),
            array('id' => 132, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'MR', 'trisim' => 'Moritanya', 'engisim' => 'Mauritania'),
            array('id' => 133, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'MU', 'trisim' => 'Mauritius', 'engisim' => 'Mauritius'),
            array('id' => 134, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'YT', 'trisim' => 'Mayotte',  'engisim' => 'Mayotte'),
            array('id' => 135, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  => 'MX', 'trisim' => 'Meksika',  'engisim' => 'Mexico'),
            array('id' => 136, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'FM', 'trisim' => 'Mikronezya', 'engisim' => 'Micronesia'),
            array('id' => 137, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'MD', 'trisim' => 'Moldova', 'engisim' => 'Moldova'),
            array('id' => 138, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'MC', 'trisim' => 'Monako', 'engisim' => 'Monaco'),
            array('id' => 139, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'MN', 'trisim' => 'Mogolistan', 'engisim' => 'Mongolia'),
            array('id' => 140, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 7, 'ulke_kodu'  =>  'MA', 'trisim' => 'Fas', 'engisim' => 'Morocco'),
            array('id' => 141, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'MZ', 'trisim' => 'Mozambik', 'engisim' => 'Mozambique'),
            array('id' => 142, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'MM', 'trisim' => 'Myanmar',  'engisim' => 'Myanmar'),
            array('id' => 143, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'NA', 'trisim' => 'Namibya',  'engisim' => 'Namibia'),
            array('id' => 144, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  => 'NR', 'trisim' => 'Nauru',  'engisim' => 'Nauru'),
            array('id' => 145, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'NP', 'trisim' => 'Nepal',  'engisim' => 'Nepal'),
            array('id' => 146, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'NL', 'trisim' => 'Hollanda', 'engisim' => 'Netherlands'),
            array('id' => 147, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'AN', 'trisim' => 'Hollanda Antilleri', 'engisim' => 'Netherlands Antilles'),
            array('id' => 148, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'NC', 'trisim' => 'Yeni Kaledonya', 'engisim' => 'New Caledonia'),
            array('id' => 149, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'NZ', 'trisim' => 'Yeni Zelanda', 'engisim' => 'New Zealand'),
            array('id' => 150, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'NI', 'trisim' => 'Nikaragua', 'engisim' => 'Nicaragua'),
            array('id' => 151, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'NE', 'trisim' => 'Nijer', 'engisim' => 'Niger'),
            array('id' => 152, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 7, 'ulke_kodu'  =>  'NG', 'trisim' => 'Nijerya', 'engisim' => 'Nigeria'),
            array('id' => 153, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  => 'NU', 'trisim' => 'Niue',  'engisim' => 'Niue'),
            array('id' => 154, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => '', 'trisim' => 'Norfolk', 'engisim' => 'Norfolk'),
            array('id' => 155, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'MP', 'trisim' => 'Kuzey Mariana Adalari', 'engisim' => 'Northern Mariana Islands'),
            array('id' => 156, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'OM', 'trisim' => 'Umman', 'engisim' => 'Oman'),
            array('id' => 157, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'PK', 'trisim' => 'Pakistan', 'engisim' => 'Pakistan'),
            array('id' => 158, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'PW', 'trisim' => 'Palau', 'engisim' => 'Palau'),
            array('id' => 159, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'PS', 'trisim' => 'Filistin', 'engisim' => 'Palestine'),
            array('id' => 160, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'PA', 'trisim' => 'Panama', 'engisim' => 'Panama'),
            array('id' => 161, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'PG', 'trisim' => 'Papua Yeni Gine', 'engisim' => 'Papua New Guinea'),
            array('id' => 162, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'PY', 'trisim' => 'Paraguay', 'engisim' => 'Paraguay'),
            array('id' => 163, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'PE', 'trisim' => 'Peru', 'engisim' => 'Peru'),
            array('id' => 164, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'PH', 'trisim' => 'Filipinler', 'engisim' => 'Philippines'),
            array('id' => 165, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'PL', 'trisim' => 'Polonya',  'engisim' => 'Poland'),
            array('id' => 166, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'PT', 'trisim' => 'Portekiz', 'engisim' => 'Portugal'),
            array('id' => 167, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  => 'PR', 'trisim' => 'Porto Riko', 'engisim' => 'Puerto Rico'),
            array('id' => 168, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'QA', 'trisim' => 'Qatar', 'engisim' => 'Qatar'),
            array('id' => 169, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'RE', 'trisim' => 'Réunion',  'engisim' => 'Réunion'),
            array('id' => 170, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'RO', 'trisim' => 'Romanya',  'engisim' => 'Romania'),
            array('id' => 171, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'RU', 'trisim' => 'Rusya',  'engisim' => 'Russia'),
            array('id' => 172, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'RW', 'trisim' => 'Ruanda', 'engisim' => 'Rwanda'),
            array('id' => 173, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 0, 'ulke_kodu'  =>  '', 'trisim' => 'Sahara', 'engisim' => 'Sahara'),
            array('id' => 174, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'SH', 'trisim' => 'Saint Helena', 'engisim' => 'Saint Helena'),
            array('id' => 175, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'KN', 'trisim' => 'Saint Kitts ve Nevis', 'engisim' => 'Saint Kitts and Nevis'),
            array('id' => 176, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'LC', 'trisim' => 'Saint Lucia', 'engisim' => 'Saint Lucia'),
            array('id' => 177, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'PM', 'trisim' => 'Saint Pierre ve Miquelon', 'engisim' => 'Saint Pierre & Miquelon'),
            array('id' => 178, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'VC', 'trisim' => 'St Vincent ve Grenadinler', 'engisim' => 'St. Vincent & the Grenadines'),
            array('id' => 179, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'WS', 'trisim' => 'Samoa', 'engisim' => 'Samoa'),
            array('id' => 180, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'SM', 'trisim' => 'San Marino', 'engisim' => 'San Marino'),
            array('id' => 181, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 0, 'ulke_kodu'  =>  'ST', 'trisim' => 'Sao Tome ve Principe', 'engisim' => 'São Tomé and Príncipe'),
            array('id' => 182, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'SA', 'trisim' => 'Suudi Arabistan', 'engisim' => 'Saudi Arabia'),
            array('id' => 183, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'SN', 'trisim' => 'Senegal', 'engisim' => 'Senegal'),
            array('id' => 184, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'RS', 'trisim' => 'Sirbistan', 'engisim' => 'Serbia and Montenegro'),
            array('id' => 185, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'SC', 'trisim' => 'Seysel Adalari', 'engisim' => 'Seychelles'),
            array('id' => 186, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 6, 'ulke_kodu'  =>  'SL', 'trisim' => 'Sierra Leone', 'engisim' => 'Sierra Leone'),
            array('id' => 187, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'SG', 'trisim' => 'Singapur',  'engisim' => 'Singapore'),
            array('id' => 188, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'SK', 'trisim' => 'Slovakya',  'engisim' => 'Slovakia'),
            array('id' => 189, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'SI', 'trisim' => 'Slovenya',  'engisim' => 'Slovenia'),
            array('id' => 190, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => '', 'trisim' => 'Smaller Territories of the UK', 'engisim' => 'Smaller Territories of the UK'),
            array('id' => 191, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'SB', 'trisim' => 'Solomon Adalari', 'engisim' => 'Solomon Islands'),
            array('id' => 192, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 4, 'ulke_kodu'  =>  'SO', 'trisim' => 'Somali', 'engisim' => 'Somalia'),
            array('id' => 193, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 7, 'ulke_kodu'  =>  'ZA', 'trisim' => 'Güney Afrika', 'engisim' => 'South Africa'),
            array('id' => 194, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'ES', 'trisim' => 'Ispanya', 'engisim' => 'Spain'),
            array('id' => 195, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'LK', 'trisim' => 'Sri Lanka', 'engisim' => 'Sri Lanka'),
            array('id' => 196, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 3, 'ulke_kodu'  =>  'SD', 'trisim' => 'Sudan', 'engisim' => 'Sudan'),
            array('id' => 197, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 8, 'ulke_kodu'  =>  'SR', 'trisim' => 'Surinam', 'engisim' => 'Suriname'),
            array('id' => 198, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'NO', 'trisim' => 'Svalbard ve Jan Mayen', 'engisim' => 'Svalbard and Jan Mayen'),
            array('id' => 199, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 2, 'ulke_kodu'  =>  'SZ', 'trisim' => 'Svaziland', 'engisim' => 'Swaziland'),
            array('id' => 200, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'SE', 'trisim' => 'Isveç', 'engisim' => 'Sweden'),
            array('id' => 201, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'CH', 'trisim' => 'Isviçre', 'engisim' => 'Switzerland'),
            array('id' => 202, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'SY', 'trisim' => 'Suriye',  'engisim' => 'Syria'),
            array('id' => 203, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'WT', 'trisim' => 'Tayvan',  'engisim' => 'Taiwan'),
            array('id' => 204, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'TJ', 'trisim' => 'Tacikistan', 'engisim' => 'Tajikistan'),
            array('id' => 205, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'TZ', 'trisim' => 'Tanzanya', 'engisim' => 'Tanzania'),
            array('id' => 206, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 0, 'ulke_kodu'  =>  '', 'trisim' => 'Terres Australes', 'engisim' => 'Terres Australes'),
            array('id' => 207, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'TH', 'trisim' => 'Tayland', 'engisim' => 'Thailand'),
            array('id' => 208, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'TG', 'trisim' => 'Togo', 'engisim' => 'Togo'),
            array('id' => 209, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'TK', 'trisim' => 'Tokelau', 'engisim' => 'Tokelau'),
            array('id' => 210, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'TO', 'trisim' => 'Tonga', 'engisim' => 'Tonga'),
            array('id' => 211, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'TT', 'trisim' => 'Trinidad ve Tobago', 'engisim' => 'Trinidad and Tobago'),
            array('id' => 212, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 6, 'ulke_kodu'  =>  'TN', 'trisim' => 'Tunus', 'engisim' => 'Tunisia'),
            array('id' => 213, 'region_id' => 2, 'country_code' => 'TR',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'TR', 'trisim' => 'Türkiye', 'engisim' => 'Türkiye'),
            array('id' => 214, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'TM', 'trisim' => 'Türkmenistan', 'engisim' => 'Turkmenistan'),
            array('id' => 215, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'TC', 'trisim' => 'Turks ve Caicos Adalari', 'engisim' => 'Turks and Caicos Islands'),
            array('id' => 216, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'TV', 'trisim' => 'Tuvalu', 'engisim' => 'Tuvalu'),
            array('id' => 217, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'UG', 'trisim' => 'Uganda',  'engisim' => 'Uganda'),
            array('id' => 218, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'UA', 'trisim' => 'Ukrayna', 'engisim' => 'Ukraine'),
            array('id' => 219, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'AE', 'trisim' => 'Birlesik Arap Emirlikleri', 'engisim' => 'United Arab Emirates'),
            array('id' => 220, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'GB', 'trisim' => 'Ingiltere', 'engisim' =>  'United Kingdom'),
            array('id' => 221, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 5,  'ulke_kodu'  => 'US', 'trisim' => 'Amerika Birlesik Devletleri', 'engisim' => 'United States of America'),
            array('id' => 222, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'UY', 'trisim' => 'Uruguay', 'engisim' => 'Uruguay'),
            array('id' => 223, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'UZ', 'trisim' => 'Özbekistan', 'engisim' => 'Uzbekistan'),
            array('id' => 224, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 9,  'ulke_kodu'  => 'VU', 'trisim' => 'Vanuatu', 'engisim' => 'Vanuatu'),
            array('id' => 225, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'VA', 'trisim' => 'Vatikan', 'engisim' => 'Vatican'),
            array('id' => 226, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'VE', 'trisim' => 'Venezuela', 'engisim' => 'Venezuela'),
            array('id' => 227, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 7,  'ulke_kodu'  => 'VN', 'trisim' => 'Vietnam', 'engisim' => 'Vietnam'),
            array('id' => 228, 'region_id' => 3, 'country_code' => 'US',  'country_phone_code' => '', 'desi_id' => 8,  'ulke_kodu'  => 'VI', 'trisim' => 'Virgin Adalari', 'engisim' => 'Virgin Islands of the USA'),
            array('id' => 229, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 0,  'ulke_kodu'  => 'WF', 'trisim' => 'Wallis ve Futuna', 'engisim' => 'Wallis & Futuna'),
            array('id' => 230, 'region_id' => 4, 'country_code' => 'AS',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'YE', 'trisim' => 'Yemen', 'engisim' => 'Yemen'),
            array('id' => 231, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'ZM', 'trisim' => 'Zambiya', 'engisim' => 'Zambia'),
            array('id' => 232, 'region_id' => 5, 'country_code' => 'AFK', 'country_phone_code' => '', 'desi_id' => 9, 'ulke_kodu'  =>  'ZW', 'trisim' => 'Zimbabve', 'engisim' => 'Zimbabwe'),
            array('id' => 233, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 2,  'ulke_kodu'  => 'GB', 'trisim' => 'Büyük Britanya', 'engisim' => 'Great Britain'),
            array('id' => 234, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'ME', 'trisim' => 'Karadag', 'engisim' => 'Karadag'),
            array('id' => 235, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 3,  'ulke_kodu'  => 'NO', 'trisim' => 'Norvec', 'engisim' => 'Norvec'),
            array('id' => 236, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 4,  'ulke_kodu'  => 'KV', 'trisim' => 'Kosova', 'engisim' => 'Kosovo'),
            array('id' => 237, 'region_id' => 1, 'country_code' => 'EU',  'country_phone_code' => '', 'desi_id' => 6,  'ulke_kodu'  => 'IC', 'trisim' => 'Kanarya Adalar', 'engisim' => 'Kanarya Adalar'),


           /*  array('id' => 1, 'code' => 'AF', 'name' => "Afghanistan", 'phonecode' => 93),
            array('id' => 2, 'code' => 'AL', 'name' => "Albania", 'phonecode' => 355),
            array('id' => 3, 'code' => 'DZ', 'name' => "Algeria", 'phonecode' => 213),
            array('id' => 4, 'code' => 'AS', 'name' => "American Samoa", 'phonecode' => 1684),
            array('id' => 5, 'code' => 'AD', 'name' => "Andorra", 'phonecode' => 376),
            array('id' => 6, 'code' => 'AO', 'name' => "Angola", 'phonecode' => 244),
            array('id' => 7, 'code' => 'AI', 'name' => "Anguilla", 'phonecode' => 1264),
            array('id' => 8, 'code' => 'AQ', 'name' => "Antarctica", 'phonecode' => 0),
            array('id' => 9, 'code' => 'AG', 'name' => "Antigua And Barbuda", 'phonecode' => 1268),
            array('id' => 10, 'code' => 'AR', 'name' => "Argentina", 'phonecode' => 54),
            array('id' => 11, 'code' => 'AM', 'name' => "Armenia", 'phonecode' => 374),
            array('id' => 12, 'code' => 'AW', 'name' => "Aruba", 'phonecode' => 297),
            array('id' => 13, 'code' => 'AU', 'name' => "Australia", 'phonecode' => 61),
            array('id' => 14, 'code' => 'AT', 'name' => "Austria", 'phonecode' => 43),
            array('id' => 15, 'code' => 'AZ', 'name' => "Azerbaijan", 'phonecode' => 994),
            array('id' => 16, 'code' => 'BS', 'name' => "Bahamas The", 'phonecode' => 1242),
            array('id' => 17, 'code' => 'BH', 'name' => "Bahrain", 'phonecode' => 973),
            array('id' => 18, 'code' => 'BD', 'name' => "Bangladesh", 'phonecode' => 880),
            array('id' => 19, 'code' => 'BB', 'name' => "Barbados", 'phonecode' => 1246),
            array('id' => 20, 'code' => 'BY', 'name' => "Belarus", 'phonecode' => 375),
            array('id' => 21, 'code' => 'BE', 'name' => "Belgium", 'phonecode' => 32),
            array('id' => 22, 'code' => 'BZ', 'name' => "Belize", 'phonecode' => 501),
            array('id' => 23, 'code' => 'BJ', 'name' => "Benin", 'phonecode' => 229),
            array('id' => 24, 'code' => 'BM', 'name' => "Bermuda", 'phonecode' => 1441),
            array('id' => 25, 'code' => 'BT', 'name' => "Bhutan", 'phonecode' => 975),
            array('id' => 26, 'code' => 'BO', 'name' => "Bolivia", 'phonecode' => 591),
            array('id' => 27, 'code' => 'BA', 'name' => "Bosnia and Herzegovina", 'phonecode' => 387),
            array('id' => 28, 'code' => 'BW', 'name' => "Botswana", 'phonecode' => 267),
            array('id' => 29, 'code' => 'BV', 'name' => "Bouvet Island", 'phonecode' => 0),
            array('id' => 30, 'code' => 'BR', 'name' => "Brazil", 'phonecode' => 55),
            array('id' => 31, 'code' => 'IO', 'name' => "British Indian Ocean Territory", 'phonecode' => 246),
            array('id' => 32, 'code' => 'BN', 'name' => "Brunei", 'phonecode' => 673),
            array('id' => 33, 'code' => 'BG', 'name' => "Bulgaria", 'phonecode' => 359),
            array('id' => 34, 'code' => 'BF', 'name' => "Burkina Faso", 'phonecode' => 226),
            array('id' => 35, 'code' => 'BI', 'name' => "Burundi", 'phonecode' => 257),
            array('id' => 36, 'code' => 'KH', 'name' => "Cambodia", 'phonecode' => 855),
            array('id' => 37, 'code' => 'CM', 'name' => "Cameroon", 'phonecode' => 237),
            array('id' => 38, 'code' => 'CA', 'name' => "Canada", 'phonecode' => 1),
            array('id' => 39, 'code' => 'CV', 'name' => "Cape Verde", 'phonecode' => 238),
            array('id' => 40, 'code' => 'KY', 'name' => "Cayman Islands", 'phonecode' => 1345),
            array('id' => 41, 'code' => 'CF', 'name' => "Central African Republic", 'phonecode' => 236),
            array('id' => 42, 'code' => 'TD', 'name' => "Chad", 'phonecode' => 235),
            array('id' => 43, 'code' => 'CL', 'name' => "Chile", 'phonecode' => 56),
            array('id' => 44, 'code' => 'CN', 'name' => "China", 'phonecode' => 86),
            array('id' => 45, 'code' => 'CX', 'name' => "Christmas Island", 'phonecode' => 61),
            array('id' => 46, 'code' => 'CC', 'name' => "Cocos (Keeling) Islands", 'phonecode' => 672),
            array('id' => 47, 'code' => 'CO', 'name' => "Colombia", 'phonecode' => 57),
            array('id' => 48, 'code' => 'KM', 'name' => "Comoros", 'phonecode' => 269),
            array('id' => 49, 'code' => 'CG', 'name' => "Congo", 'phonecode' => 242),
            array('id' => 50, 'code' => 'CD', 'name' => "Congo The Democratic Republic Of The", 'phonecode' => 242),
            array('id' => 51, 'code' => 'CK', 'name' => "Cook Islands", 'phonecode' => 682),
            array('id' => 52, 'code' => 'CR', 'name' => "Costa Rica", 'phonecode' => 506),
            array('id' => 53, 'code' => 'CI', 'name' => "Cote D Ivoire (Ivory Coast)", 'phonecode' => 225),
            array('id' => 54, 'code' => 'HR', 'name' => "Croatia (Hrvatska)", 'phonecode' => 385),
            array('id' => 55, 'code' => 'CU', 'name' => "Cuba", 'phonecode' => 53),
            array('id' => 56, 'code' => 'CY', 'name' => "Cyprus", 'phonecode' => 357),
            array('id' => 57, 'code' => 'CZ', 'name' => "Czech Republic", 'phonecode' => 420),
            array('id' => 58, 'code' => 'DK', 'name' => "Denmark", 'phonecode' => 45),
            array('id' => 59, 'code' => 'DJ', 'name' => "Djibouti", 'phonecode' => 253),
            array('id' => 60, 'code' => 'DM', 'name' => "Dominica", 'phonecode' => 1767),
            array('id' => 61, 'code' => 'DO', 'name' => "Dominican Republic", 'phonecode' => 1809),
            array('id' => 62, 'code' => 'TP', 'name' => "East Timor", 'phonecode' => 670),
            array('id' => 63, 'code' => 'EC', 'name' => "Ecuador", 'phonecode' => 593),
            array('id' => 64, 'code' => 'EG', 'name' => "Egypt", 'phonecode' => 20),
            array('id' => 65, 'code' => 'SV', 'name' => "El Salvador", 'phonecode' => 503),
            array('id' => 66, 'code' => 'GQ', 'name' => "Equatorial Guinea", 'phonecode' => 240),
            array('id' => 67, 'code' => 'ER', 'name' => "Eritrea", 'phonecode' => 291),
            array('id' => 68, 'code' => 'EE', 'name' => "Estonia", 'phonecode' => 372),
            array('id' => 69, 'code' => 'ET', 'name' => "Ethiopia", 'phonecode' => 251),
            array('id' => 70, 'code' => 'XA', 'name' => "External Territories of Australia", 'phonecode' => 61),
            array('id' => 71, 'code' => 'FK', 'name' => "Falkland Islands", 'phonecode' => 500),
            array('id' => 72, 'code' => 'FO', 'name' => "Faroe Islands", 'phonecode' => 298),
            array('id' => 73, 'code' => 'FJ', 'name' => "Fiji Islands", 'phonecode' => 679),
            array('id' => 74, 'code' => 'FI', 'name' => "Finland", 'phonecode' => 358),
            array('id' => 75, 'code' => 'FR', 'name' => "France", 'phonecode' => 33),
            array('id' => 76, 'code' => 'GF', 'name' => "French Guiana", 'phonecode' => 594),
            array('id' => 77, 'code' => 'PF', 'name' => "French Polynesia", 'phonecode' => 689),
            array('id' => 78, 'code' => 'TF', 'name' => "French Southern Territories", 'phonecode' => 0),
            array('id' => 79, 'code' => 'GA', 'name' => "Gabon", 'phonecode' => 241),
            array('id' => 80, 'code' => 'GM', 'name' => "Gambia The", 'phonecode' => 220),
            array('id' => 81, 'code' => 'GE', 'name' => "Georgia", 'phonecode' => 995),
            array('id' => 82, 'code' => 'DE', 'name' => "Germany", 'phonecode' => 49),
            array('id' => 83, 'code' => 'GH', 'name' => "Ghana", 'phonecode' => 233),
            array('id' => 84, 'code' => 'GI', 'name' => "Gibraltar", 'phonecode' => 350),
            array('id' => 85, 'code' => 'GR', 'name' => "Greece", 'phonecode' => 30),
            array('id' => 86, 'code' => 'GL', 'name' => "Greenland", 'phonecode' => 299),
            array('id' => 87, 'code' => 'GD', 'name' => "Grenada", 'phonecode' => 1473),
            array('id' => 88, 'code' => 'GP', 'name' => "Guadeloupe", 'phonecode' => 590),
            array('id' => 89, 'code' => 'GU', 'name' => "Guam", 'phonecode' => 1671),
            array('id' => 90, 'code' => 'GT', 'name' => "Guatemala", 'phonecode' => 502),
            array('id' => 91, 'code' => 'XU', 'name' => "Guernsey and Alderney", 'phonecode' => 44),
            array('id' => 92, 'code' => 'GN', 'name' => "Guinea", 'phonecode' => 224),
            array('id' => 93, 'code' => 'GW', 'name' => "Guinea-Bissau", 'phonecode' => 245),
            array('id' => 94, 'code' => 'GY', 'name' => "Guyana", 'phonecode' => 592),
            array('id' => 95, 'code' => 'HT', 'name' => "Haiti", 'phonecode' => 509),
            array('id' => 96, 'code' => 'HM', 'name' => "Heard and McDonald Islands", 'phonecode' => 0),
            array('id' => 97, 'code' => 'HN', 'name' => "Honduras", 'phonecode' => 504),
            array('id' => 98, 'code' => 'HK', 'name' => "Hong Kong S.A.R.", 'phonecode' => 852),
            array('id' => 99, 'code' => 'HU', 'name' => "Hungary", 'phonecode' => 36),
            array('id' => 100, 'code' => 'IS', 'name' => "Iceland", 'phonecode' => 354),
            array('id' => 101, 'code' => 'IN', 'name' => "India", 'phonecode' => 91),
            array('id' => 102, 'code' => 'ID', 'name' => "Indonesia", 'phonecode' => 62),
            array('id' => 103, 'code' => 'IR', 'name' => "Iran", 'phonecode' => 98),
            array('id' => 104, 'code' => 'IQ', 'name' => "Iraq", 'phonecode' => 964),
            array('id' => 105, 'code' => 'IE', 'name' => "Ireland", 'phonecode' => 353),
            array('id' => 106, 'code' => 'IL', 'name' => "Israel", 'phonecode' => 972),
            array('id' => 107, 'code' => 'IT', 'name' => "Italy", 'phonecode' => 39),
            array('id' => 108, 'code' => 'JM', 'name' => "Jamaica", 'phonecode' => 1876),
            array('id' => 109, 'code' => 'JP', 'name' => "Japan", 'phonecode' => 81),
            array('id' => 110, 'code' => 'XJ', 'name' => "Jersey", 'phonecode' => 44),
            array('id' => 111, 'code' => 'JO', 'name' => "Jordan", 'phonecode' => 962),
            array('id' => 112, 'code' => 'KZ', 'name' => "Kazakhstan", 'phonecode' => 7),
            array('id' => 113, 'code' => 'KE', 'name' => "Kenya", 'phonecode' => 254),
            array('id' => 114, 'code' => 'KI', 'name' => "Kiribati", 'phonecode' => 686),
            array('id' => 115, 'code' => 'KP', 'name' => "Korea North", 'phonecode' => 850),
            array('id' => 116, 'code' => 'KR', 'name' => "Korea South", 'phonecode' => 82),
            array('id' => 117, 'code' => 'KW', 'name' => "Kuwait", 'phonecode' => 965),
            array('id' => 118, 'code' => 'KG', 'name' => "Kyrgyzstan", 'phonecode' => 996),
            array('id' => 119, 'code' => 'LA', 'name' => "Laos", 'phonecode' => 856),
            array('id' => 120, 'code' => 'LV', 'name' => "Latvia", 'phonecode' => 371),
            array('id' => 121, 'code' => 'LB', 'name' => "Lebanon", 'phonecode' => 961),
            array('id' => 122, 'code' => 'LS', 'name' => "Lesotho", 'phonecode' => 266),
            array('id' => 123, 'code' => 'LR', 'name' => "Liberia", 'phonecode' => 231),
            array('id' => 124, 'code' => 'LY', 'name' => "Libya", 'phonecode' => 218),
            array('id' => 125, 'code' => 'LI', 'name' => "Liechtenstein", 'phonecode' => 423),
            array('id' => 126, 'code' => 'LT', 'name' => "Lithuania", 'phonecode' => 370),
            array('id' => 127, 'code' => 'LU', 'name' => "Luxembourg", 'phonecode' => 352),
            array('id' => 128, 'code' => 'MO', 'name' => "Macau S.A.R.", 'phonecode' => 853),
            array('id' => 129, 'code' => 'MK', 'name' => "Macedonia", 'phonecode' => 389),
            array('id' => 130, 'code' => 'MG', 'name' => "Madagascar", 'phonecode' => 261),
            array('id' => 131, 'code' => 'MW', 'name' => "Malawi", 'phonecode' => 265),
            array('id' => 132, 'code' => 'MY', 'name' => "Malaysia", 'phonecode' => 60),
            array('id' => 133, 'code' => 'MV', 'name' => "Maldives", 'phonecode' => 960),
            array('id' => 134, 'code' => 'ML', 'name' => "Mali", 'phonecode' => 223),
            array('id' => 135, 'code' => 'MT', 'name' => "Malta", 'phonecode' => 356),
            array('id' => 136, 'code' => 'XM', 'name' => "Man (Isle of)", 'phonecode' => 44),
            array('id' => 137, 'code' => 'MH', 'name' => "Marshall Islands", 'phonecode' => 692),
            array('id' => 138, 'code' => 'MQ', 'name' => "Martinique", 'phonecode' => 596),
            array('id' => 139, 'code' => 'MR', 'name' => "Mauritania", 'phonecode' => 222),
            array('id' => 140, 'code' => 'MU', 'name' => "Mauritius", 'phonecode' => 230),
            array('id' => 141, 'code' => 'YT', 'name' => "Mayotte", 'phonecode' => 269),
            array('id' => 142, 'code' => 'MX', 'name' => "Mexico", 'phonecode' => 52),
            array('id' => 143, 'code' => 'FM', 'name' => "Micronesia", 'phonecode' => 691),
            array('id' => 144, 'code' => 'MD', 'name' => "Moldova", 'phonecode' => 373),
            array('id' => 145, 'code' => 'MC', 'name' => "Monaco", 'phonecode' => 377),
            array('id' => 146, 'code' => 'MN', 'name' => "Mongolia", 'phonecode' => 976),
            array('id' => 147, 'code' => 'MS', 'name' => "Montserrat", 'phonecode' => 1664),
            array('id' => 148, 'code' => 'MA', 'name' => "Morocco", 'phonecode' => 212),
            array('id' => 149, 'code' => 'MZ', 'name' => "Mozambique", 'phonecode' => 258),
            array('id' => 150, 'code' => 'MM', 'name' => "Myanmar", 'phonecode' => 95),
            array('id' => 151, 'code' => 'NA', 'name' => "Namibia", 'phonecode' => 264),
            array('id' => 152, 'code' => 'NR', 'name' => "Nauru", 'phonecode' => 674),
            array('id' => 153, 'code' => 'NP', 'name' => "Nepal", 'phonecode' => 977),
            array('id' => 154, 'code' => 'AN', 'name' => "Netherlands Antilles", 'phonecode' => 599),
            array('id' => 155, 'code' => 'NL', 'name' => "Netherlands The", 'phonecode' => 31),
            array('id' => 156, 'code' => 'NC', 'name' => "New Caledonia", 'phonecode' => 687),
            array('id' => 157, 'code' => 'NZ', 'name' => "New Zealand", 'phonecode' => 64),
            array('id' => 158, 'code' => 'NI', 'name' => "Nicaragua", 'phonecode' => 505),
            array('id' => 159, 'code' => 'NE', 'name' => "Niger", 'phonecode' => 227),
            array('id' => 160, 'code' => 'NG', 'name' => "Nigeria", 'phonecode' => 234),
            array('id' => 161, 'code' => 'NU', 'name' => "Niue", 'phonecode' => 683),
            array('id' => 162, 'code' => 'NF', 'name' => "Norfolk Island", 'phonecode' => 672),
            array('id' => 163, 'code' => 'MP', 'name' => "Northern Mariana Islands", 'phonecode' => 1670),
            array('id' => 164, 'code' => 'NO', 'name' => "Norway", 'phonecode' => 47),
            array('id' => 165, 'code' => 'OM', 'name' => "Oman", 'phonecode' => 968),
            array('id' => 166, 'code' => 'PK', 'name' => "Pakistan", 'phonecode' => 92),
            array('id' => 167, 'code' => 'PW', 'name' => "Palau", 'phonecode' => 680),
            array('id' => 168, 'code' => 'PS', 'name' => "Palestinian Territory Occupied", 'phonecode' => 970),
            array('id' => 169, 'code' => 'PA', 'name' => "Panama", 'phonecode' => 507),
            array('id' => 170, 'code' => 'PG', 'name' => "Papua new Guinea", 'phonecode' => 675),
            array('id' => 171, 'code' => 'PY', 'name' => "Paraguay", 'phonecode' => 595),
            array('id' => 172, 'code' => 'PE', 'name' => "Peru", 'phonecode' => 51),
            array('id' => 173, 'code' => 'PH', 'name' => "Philippines", 'phonecode' => 63),
            array('id' => 174, 'code' => 'PN', 'name' => "Pitcairn Island", 'phonecode' => 0),
            array('id' => 175, 'code' => 'PL', 'name' => "Poland", 'phonecode' => 48),
            array('id' => 176, 'code' => 'PT', 'name' => "Portugal", 'phonecode' => 351),
            array('id' => 177, 'code' => 'PR', 'name' => "Puerto Rico", 'phonecode' => 1787),
            array('id' => 178, 'code' => 'QA', 'name' => "Qatar", 'phonecode' => 974),
            array('id' => 179, 'code' => 'RE', 'name' => "Reunion", 'phonecode' => 262),
            array('id' => 180, 'code' => 'RO', 'name' => "Romania", 'phonecode' => 40),
            array('id' => 181, 'code' => 'RU', 'name' => "Russia", 'phonecode' => 70),
            array('id' => 182, 'code' => 'RW', 'name' => "Rwanda", 'phonecode' => 250),
            array('id' => 183, 'code' => 'SH', 'name' => "Saint Helena", 'phonecode' => 290),
            array('id' => 184, 'code' => 'KN', 'name' => "Saint Kitts And Nevis", 'phonecode' => 1869),
            array('id' => 185, 'code' => 'LC', 'name' => "Saint Lucia", 'phonecode' => 1758),
            array('id' => 186, 'code' => 'PM', 'name' => "Saint Pierre and Miquelon", 'phonecode' => 508),
            array('id' => 187, 'code' => 'VC', 'name' => "Saint Vincent And The Grenadines", 'phonecode' => 1784),
            array('id' => 188, 'code' => 'WS', 'name' => "Samoa", 'phonecode' => 684),
            array('id' => 189, 'code' => 'SM', 'name' => "San Marino", 'phonecode' => 378),
            array('id' => 190, 'code' => 'ST', 'name' => "Sao Tome and Principe", 'phonecode' => 239),
            array('id' => 191, 'code' => 'SA', 'name' => "Saudi Arabia", 'phonecode' => 966),
            array('id' => 192, 'code' => 'SN', 'name' => "Senegal", 'phonecode' => 221),
            array('id' => 193, 'code' => 'RS', 'name' => "Serbia", 'phonecode' => 381),
            array('id' => 194, 'code' => 'SC', 'name' => "Seychelles", 'phonecode' => 248),
            array('id' => 195, 'code' => 'SL', 'name' => "Sierra Leone", 'phonecode' => 232),
            array('id' => 196, 'code' => 'SG', 'name' => "Singapore", 'phonecode' => 65),
            array('id' => 197, 'code' => 'SK', 'name' => "Slovakia", 'phonecode' => 421),
            array('id' => 198, 'code' => 'SI', 'name' => "Slovenia", 'phonecode' => 386),
            array('id' => 199, 'code' => 'XG', 'name' => "Smaller Territories of the UK", 'phonecode' => 44),
            array('id' => 200, 'code' => 'SB', 'name' => "Solomon Islands", 'phonecode' => 677),
            array('id' => 201, 'code' => 'SO', 'name' => "Somalia", 'phonecode' => 252),
            array('id' => 202, 'code' => 'ZA', 'name' => "South Africa", 'phonecode' => 27),
            array('id' => 203, 'code' => 'GS', 'name' => "South Georgia", 'phonecode' => 0),
            array('id' => 204, 'code' => 'SS', 'name' => "South Sudan", 'phonecode' => 211),
            array('id' => 205, 'code' => 'ES', 'name' => "Spain", 'phonecode' => 34),
            array('id' => 206, 'code' => 'LK', 'name' => "Sri Lanka", 'phonecode' => 94),
            array('id' => 207, 'code' => 'SD', 'name' => "Sudan", 'phonecode' => 249),
            array('id' => 208, 'code' => 'SR', 'name' => "Suriname", 'phonecode' => 597),
            array('id' => 209, 'code' => 'SJ', 'name' => "Svalbard And Jan Mayen Islands", 'phonecode' => 47),
            array('id' => 210, 'code' => 'SZ', 'name' => "Swaziland", 'phonecode' => 268),
            array('id' => 211, 'code' => 'SE', 'name' => "Sweden", 'phonecode' => 46),
            array('id' => 212, 'code' => 'CH', 'name' => "Switzerland", 'phonecode' => 41),
            array('id' => 213, 'code' => 'SY', 'name' => "Syria", 'phonecode' => 963),
            array('id' => 214, 'code' => 'TW', 'name' => "Taiwan", 'phonecode' => 886),
            array('id' => 215, 'code' => 'TJ', 'name' => "Tajikistan", 'phonecode' => 992),
            array('id' => 216, 'code' => 'TZ', 'name' => "Tanzania", 'phonecode' => 255),
            array('id' => 217, 'code' => 'TH', 'name' => "Thailand", 'phonecode' => 66),
            array('id' => 218, 'code' => 'TG', 'name' => "Togo", 'phonecode' => 228),
            array('id' => 219, 'code' => 'TK', 'name' => "Tokelau", 'phonecode' => 690),
            array('id' => 220, 'code' => 'TO', 'name' => "Tonga", 'phonecode' => 676),
            array('id' => 221, 'code' => 'TT', 'name' => "Trinidad And Tobago", 'phonecode' => 1868),
            array('id' => 222, 'code' => 'TN', 'name' => "Tunisia", 'phonecode' => 216),
            array('id' => 223, 'code' => 'TR', 'name' => "Turkey", 'phonecode' => 90),
            array('id' => 224, 'code' => 'TM', 'name' => "Turkmenistan", 'phonecode' => 7370),
            array('id' => 225, 'code' => 'TC', 'name' => "Turks And Caicos Islands", 'phonecode' => 1649),
            array('id' => 226, 'code' => 'TV', 'name' => "Tuvalu", 'phonecode' => 688),
            array('id' => 227, 'code' => 'UG', 'name' => "Uganda", 'phonecode' => 256),
            array('id' => 228, 'code' => 'UA', 'name' => "Ukraine", 'phonecode' => 380),
            array('id' => 229, 'code' => 'AE', 'name' => "United Arab Emirates", 'phonecode' => 971),
            array('id' => 230, 'code' => 'GB', 'name' => "United Kingdom", 'phonecode' => 44),
            array('id' => 231, 'code' => 'US', 'name' => "United States", 'phonecode' => 1),
            array('id' => 232, 'code' => 'UM', 'name' => "United States Minor Outlying Islands", 'phonecode' => 1),
            array('id' => 233, 'code' => 'UY', 'name' => "Uruguay", 'phonecode' => 598),
            array('id' => 234, 'code' => 'UZ', 'name' => "Uzbekistan", 'phonecode' => 998),
            array('id' => 235, 'code' => 'VU', 'name' => "Vanuatu", 'phonecode' => 678),
            array('id' => 236, 'code' => 'VA', 'name' => "Vatican City State (Holy See)", 'phonecode' => 39),
            array('id' => 237, 'code' => 'VE', 'name' => "Venezuela", 'phonecode' => 58),
            array('id' => 238, 'code' => 'VN', 'name' => "Vietnam", 'phonecode' => 84),
            array('id' => 239, 'code' => 'VG', 'name' => "Virgin Islands (British)", 'phonecode' => 1284),
            array('id' => 240, 'code' => 'VI', 'name' => "Virgin Islands (US)", 'phonecode' => 1340),
            array('id' => 241, 'code' => 'WF', 'name' => "Wallis And Futuna Islands", 'phonecode' => 681),
            array('id' => 242, 'code' => 'EH', 'name' => "Western Sahara", 'phonecode' => 212),
            array('id' => 243, 'code' => 'YE', 'name' => "Yemen", 'phonecode' => 967),
            array('id' => 244, 'code' => 'YU', 'name' => "Yugoslavia", 'phonecode' => 38),
            array('id' => 245, 'code' => 'ZM', 'name' => "Zambia", 'phonecode' => 260),
            array('id' => 246, 'code' => 'ZW', 'name' => "Zimbabwe", 'phonecode' => 263), */
        );
        DB::table('countries')->insert($countries);
    }
}